### ISSUE TITLE
How To Configure/Setup Webpanel?

### ISSUE THREAD

**Issue by Nadawr** [Epix-Incorporated/Adonis#1009]
Im Making An Roblox Game With Adonis, I Gonna Need More Things For Moderation, I Need To Know How To Configure/Setup Web Panel, Can Someone Help Me Doing That?

**Comment by NoobBucket** [comment]
Webpanel is very unstable currently, so it is not recommended for use unfortunately.

**Comment by watameln** [comment]
> 

you wait until they fix it.

**Comment by Nadawr** [comment]
I Gonna Need An Full Guide but theses anwsers can be true but i gonna need get an anwser of the adonis Devolpers

**Comment by Expertcoderz** [comment]
The webpanel is an experimental Adonis feature and as others mentioned it can be quite unstable/unreliable.

We do not recommend using the webpanel unless you intend to test it. It offers no additional moderation features to what Adonis already includes.

**Comment by Nadawr** [comment]
Okay So Tell Me When It Gets Unexperimental, Thanks For The Anwser
