### ISSUE TITLE
Separate Documentation Website Rather Than Using GitHub Wiki

### ISSUE THREAD

**Issue by EgizianoEG** [Epix-Incorporated/Adonis#1012]
Github Wiki it is not the most effective thing for creating comprehensive and user-friendly documentation. I suggest creating a separate documentation site, which would allow for better organization and presentation of information.

Two potential options for creating such a site are [Docusaurus](https://docusaurus.io) and [Material for Mkdocs](https://squidfunk.github.io/mkdocs-material), both of which have a variety of features that could be useful for the documentation needs.

**Comment by NoobBucket** [comment]
Agree, although github pages would be ideal since it would be part of here, but not complicated like the wiki

**Comment by WaviestBalloon** [comment]
It's very hard to search for things on GitHub's wiki, Docusaurus looks very promising.

**Comment by P3tray** [comment]
This requires updating the Wiki. Back in my day Adonis didn't have a wiki! We had to hike 5 miles in the freezing cold searching for code snippets. Kids like you have it easy! Quit complaining! I'll hit you with my Zimmer frame!

**Comment by WaviestBalloon** [comment]
Calm down P3foodtray

**Comment by LiveFireExercise** [comment]
So you guys want a non-GitHub wiki

**Comment by moo1210** [comment]
would be cool but kind of useless at the same time, someone would probably just make a PR, screw up half of the documentation, and no one would care lol. not really sure what much there is to document anyway outside of settings file stuff.

**Comment by LiveFireExercise** [comment]
Yea
