### ISSUE TITLE
Customizing Adonis: An Override Mechanism for Default Scripts, Models, Folders, and Packages

### ISSUE THREAD

**Issue by EgizianoEG** [Epix-Incorporated/Adonis#1014]
### Description:
We might want to replace some of the included scripts in Adonis, while still being able to receive Adonis updates without having to manually reinsert updated scripts. For example, we may want to replace the default HTTP module with a customized module that has the same functionality but is better suited for our specific use case. In such cases, Adonis should look for any override modules before requiring the default ones. If an override module with the same location and name exists, it should be required instead of the default one.

### How this feature could be implemented:

When Adonis loads and requires its sub-modules, it should first search for any overrides before loading the default sub-modules. This should apply to all folders, so if a folder named "Assets" exists under "Adonis\Config\Overriddes\Server\Dependencies", Adonis should replace any matching child files within that path with the overridden ones, if they exist. If the "Assets" folder is empty in the overrides directory, Adonis should not remove any of the files inside its *original Assets directory*.

For better explanation and live example, you can check Material for Mkdocs customization page, specifically, [Setup and theme structure](https://squidfunk.github.io/mkdocs-material/customization/#setup-and-theme-structure).

### How it can be used:

Let's say we want to replace a module script in the structure of the main module, specifically the "TrelloAPI" module. Its path under the main module is "Server\Dependencies\TrelloAPI". 

- To replace it, we will need to create a folder under the "Overrides" folder called "Server", and then another one under "Server" called "Dependencies".

- After completing the first step, we can then create a new module script or copy the original one and make any necessary edits. However, it is essential to ensure that the name of the module is the same as the original one we wish to override, which in this case would be "TrelloAPI" or a new module will be added to the Adonis' Dependencies folder if it doesn't exist already.
![image](https://user-images.githubusercontent.com/56704274/220707101-2dc0c844-3560-4546-a9c0-94c7a006b55c.png)

- Adonis should now require the modified TrelloAPI instead of the default one and be able to call and use it externally without needing another module outside the Adonis environment.

**Comment by Sceleratis** [comment]
Plugin modules are loaded after the default core modules and can replace anything Adonis uses in it's server/client tables (which is where it pulls stuff like HTTP methods.)

A plugin that just replaces server.HTTP with something fully custom should do what you're asking.

**Comment by P3tray** [comment]
As Sceleratis said, already a feature. I already replace all of HTTP and Trello myself with a plugin aptly named `Server-HTTP`, and I put TrelloAPI underneath it and swap the require to be `script.TrelloAPI`. HTTP defines the location of TrelloAPI for the rest of Adonis, so no more script modifications need to be made. I'm not sure how this wasn't immediately obvious a functionality of plugins? It's still a rare case you need to override the entire file, I had only done it with HTTP because of how basic it is as a file, and the fact I also replace all of TrelloAPI. I can be handy to clone an entire file and do a diffcheck later on to convert it to a plugin with only the modified changes, that way Adonis will load faster.

**Comment by simulified** [comment]
There is a problem
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 1000; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by watameln** [comment]
Maadi
