### ISSUE TITLE
Spelling mistake in Wiki

### ISSUE THREAD

**Issue by NoobBucket** [Epix-Incorporated/Adonis#1032]
Wiki: Server.Admin has a typo "SearchComamnds".
Link: https://github.com/Epix-Incorporated/Adonis/wiki/Tables:-server.Admin#searchcomamnds-player-object-search-string:~:text=true%20if%20allowed-,SearchComamnds,-(Player%20(Object)%2C%20Search

**Comment by P3tray** [comment]
@Expertcoderz literally unusable

**Comment by EasternBloxxer** [comment]
how do i edit the wiki again

**Comment by LiveFireExercise** [comment]
You don't only GitHub editors can
