### ISSUE TITLE
How can I set certain ranks to have 0 power?

### ISSUE THREAD

**Issue by Jxyxpro** [Epix-Incorporated/Adonis#1039]
Hello Adonis! My names Jay and I am developer for my ro-school. I have recently added Adonis admin into my game on roblox studio, tested the admin out with different ranks on my game and found out that the ranks I don't want to have admin, do have admin. So I looked on the script and it says something like “players - 0 power” but I don’t know where I can put these rank for them to have 0 power. How and where to I add certain ranks to have no admin commands at all?

**Comment by ccuser44** [comment]
> Hello Adonis! My names Jay and I am developer for my ro-school. I have recently added Adonis admin into my game on roblox studio, tested the admin out with different ranks on my game and found out that the ranks I don't want to have admin, do have admin. So I looked on the script and it says something like “players - 0 power” but I don’t know where I can put these rank for them to have 0 power. How and where to I add certain ranks to have no admin commands at all?

```
settings.Ranks = {
	["Moderators"] = {
		Level = 100;
		Users = {
			--// Add users here
		};
	};
 
	["Admins"] = {
		Level = 200;
		Users = {
			--// Add users here
		};
	};
 
	["HeadAdmins"] = {
		Level = 300;
		Users = {
			--// Add users here
		};
	};
 
	["Creators"] = {
		Level = 900; --// Anything 900 or higher will be considered a creator and will bypass all perms & be allowed to edit settings in-game.
		Users = {
			--// Add users here (Also, don't forget quotations and all that)
		};
	};
};
```

**Comment by ccuser44** [comment]
Change `Level =` to 0
