### ISSUE TITLE
FLY BUG: MaxForce and MaxTorque

### ISSUE THREAD

**Issue by dorhdr** [Epix-Incorporated/Adonis#1052]
![image](https://user-images.githubusercontent.com/33329672/230512628-6df28acb-ae20-4653-b9ff-1fdf9695a40a.png)
**Location**: Server.Dependencies.Assets.Fly
_I fixed it by doing this here on the line where it has bPos.MaxForce and bGyro.MaxTorque. The same thing happens in function Stop()_

``local as = Vector3.new(math.huge, math.huge, math.huge)``

	bPos.Position = part.Position
	bPos.MaxForce = as

	bGyro.CFrame = part.CFrame
	bGyro.MaxTorque = as

**Comment by ccuser44** [comment]
Do you happen to have any plugins?

**Comment by dorhdr** [comment]
> 

Yes, I have but it's only for Discord Webhook and delivering tags.

**Comment by ccuser44** [comment]
This has been fixed (at least in the nightly) so the issue can be closed

**Comment by Dimenpsyonal** [comment]
Awesome
