### ISSUE TITLE
Admin GUI disables after :ref command is used

### ISSUE THREAD

**Issue by loggerheadlogan1** [Epix-Incorporated/Adonis#1055]
- What are the steps that lead to the bug occurring? **After the :refresh command is used** Or, how frequently does the bug occur? **Every time**
- What would be the normally expected or desired result? **No**
- What is the actual result (the bug)? **GUI for admin commands no longer comes up**
- What is the impact of this bug? **Players must use chat to execute commands**
- (Any additional context or information eg. in the form of error messages or screenshots.)

**Comment by coasterteam** [comment]
We are actively investigating this at the moment, apologies for the inconvenience.

**Comment by karl-police** [comment]
I think this is fixed. I did Refresh and nothing disappeared. And this #949 was closed for some reason.

@coasterteam 😭 you put INVESTIGATING on it, but you never came back

**Comment by WaviestBalloon** [comment]
> I think this is fixed. I did Refresh and nothing disappeared. And this #949 was closed for some reason.
> 
> @coasterteam 😭 you put INVESTIGATING on it, but you never came back

#949 was closed due to it not being replicable and the creator of the issue never responded back with more information on the bug.

Neither can I replicate this issue: 
![image](https://github.com/Epix-Incorporated/Adonis/assets/31796727/35abc1b6-6aa3-4864-884b-cd32227a07df)

I ran `:refresh`, but I can still access the command bar, it would be really helpful if @loggerheadlogan1 can attach a recording of the issue.

**Comment by WaviestBalloon** [comment]
Closure of this issue when @coasterteam/@Expertcoderz?
You have got to do some spring cleaning on the Issues panel of Adonis :(

**Comment by ccuser44** [comment]
This doesn't appear in nightly for me so this might be fixed

**Comment by Dimenpsyonal** [comment]
> You have got to do some spring cleaning on the Issues panel of Adonis

Ha! Haha! Good one

**Comment by WaviestBalloon** [comment]
> Ha! Haha! Good one

![F9GWuGQbAAALf8b](https://github.com/Epix-Incorporated/Adonis/assets/31796727/0033fbc4-fc03-4cd6-adc7-8d79932edc83)
