### ISSUE TITLE
Adonis not loading plugins.

### ISSUE THREAD

**Issue by RadiantUwU** [Epix-Incorporated/Adonis#1073]
- What are the steps that lead to the bug occurring? Or, how frequently does the bug occur?
    Create a server plugin.
- What would be the normally expected or desired result? It should print the debug message inside the plugin
- What is the actual result (the bug)? It does not print the debug message, and doesn't seem to be loading them.
- What is the impact of this bug? Plugin not loading.
- (Any additional context or information eg. in the form of error messages or screenshots.)
[I have given you creator powers to debug if needed.](https://www.roblox.com/games/12742487540/Wabels-Concert)
![image](https://user-images.githubusercontent.com/69520693/230745371-fc5f6c1f-152b-4f4c-95a1-d85599c92473.png)
![image](https://user-images.githubusercontent.com/69520693/230745382-2174ccf0-ee39-41ef-8147-6222bffafc0c.png)
![image](https://user-images.githubusercontent.com/69520693/230745426-3b9ea7d1-8196-4fd1-a510-c6e7ccd13a60.png)

**Comment by NoobBucket** [comment]
try

`return function(Vargs)
local Commands = Vargs.Server.Commands
local Settings = Vargs.Server.Settings`

**Comment by RadiantUwU** [comment]
Issue fixed
