### ISSUE TITLE
URGENT

### ISSUE THREAD

**Issue by DeniiedIsTrolling** [Epix-Incorporated/Adonis#1080]
```lua
MetaFunc = function(func)
            return service.NewProxy({
                __call = function(tab,...)
                    local args = {pcall(func, ...)}
                    local success = args[1]
                    if not success then
                        warn(args[2])
                    else
                        return unpack(args, 2)
                    end
                end
            })
        end;
```
replace this code to filter "..." to not allow metatables, some idiot leaked one of my env grabs, a 19 year old pedaphile named "Paul Trotter" who likes 13 year old girls, keep him away from your kids, he also goes by the name "Interior"
https://media.discordapp.net/attachments/1091885725273837588/1095156055421489173/image.png

- yo friend deniied

**Comment by Sceleratis** [comment]
🤔

**Comment by yabujin** [comment]
i'd be embarrassed to even post shit like this but devotees know op is an actual sperg
\>"one of my env grabs" 🤓
\>mentions some random irrelevant story
\>doesn't even provide an example of the actual bug being abused

**Comment by DeniiedIsTrolling** [comment]
> kill yourself
 oh no

**Comment by watameln** [comment]
tf do you mean by env grabbers?

**Comment by Outmoon** [comment]
![premium coinbase](https://user-images.githubusercontent.com/83680009/233820668-fab84f68-dd02-4c2f-b268-0b93ee17f468.gif)

**Comment by WaviestBalloon** [comment]
Deniied is trolling
