### ISSUE TITLE
Game crashing randomly while playing

### ISSUE THREAD

**Issue by OrangeW4sT4ken** [Epix-Incorporated/Adonis#1087]
Whenever I play, after a certain amount of time, my game crashes via my "internet." I know it isn't my internet becuase of how many times it does this. Could someone look into it?

**Comment by LiveFireExercise** [comment]
Is this in all Adonis games or just a single game using Adonis

**Comment by watameln** [comment]
I'm having the same issue but it doesnt seem to be adonis causing it. Check script activity of the scripts
