### ISSUE TITLE
:view doesnt work as intended

### ISSUE THREAD

**Issue by WalkerOfBacon** [Epix-Incorporated/Adonis#1094]
Whenever you run :view [whether you view yourself or others] it always returns "<player> doesn't have a character humanoid".
Would appreciate if someone looked into it [because I could not]

**Comment by FungusGenerator** [comment]
Is this still happening? If so, can you give some info and a screenshot of the error

**Comment by WalkerOfBacon** [comment]
> Is this still happening? If so, can you give some info and a screenshot of the error

It is still happening
![image](https://user-images.githubusercontent.com/50679909/233858184-656774d2-ab1c-4002-b6d9-99f5a449f9ee.png)

**Comment by ccuser44** [comment]
> > Is this still happening? If so, can you give some info and a screenshot of the error
> 
> It is still happening ![image](https://user-images.githubusercontent.com/50679909/233858184-656774d2-ab1c-4002-b6d9-99f5a449f9ee.png)

I cannot reproduce this.

Could you please tell:

- Are you using the most recent version of the Adonis mainmodule (Type `:changelog` to see it)
- Are you using any plugins in Adonis?
- Does this affect R6 or R15 characters?
- Are the characters custom in any way?
- Does this only happen in your game or in all games. Does it happen on <https://www.roblox.com/games/321602473/Adonis-Admin-Sandbox> too?

**Comment by FungusGenerator** [comment]
I also can't, another script may be tampering with the character. Can you try this on a different place?

**Comment by WalkerOfBacon** [comment]
> I cannot reproduce this.
> 
> Could you please tell:
> 
> * Are you using the most recent version of the Adonis mainmodule (Type `:changelog` to see it)
> * Are you using any plugins in Adonis?
> * Does this affect R6 or R15 characters?
> * Are the characters custom in any way?
> * Does this only happen in your game or in all games. Does it happen on https://www.roblox.com/games/321602473/Adonis-Admin-Sandbox too?

I double checked just now. Apparently the problem doesn't exist anymore.

Weird
