### ISSUE TITLE
console player selection does not work anymore

### ISSUE THREAD

**Issue by FuhrerDox** [Epix-Incorporated/Adonis#1109]
1- What are the steps that lead to the bug occurring? Or, how frequently does the bug occur?
2- What would be the normally expected or desired result?
3- What is the actual result (the bug)?
4- What is the impact of this bug?
5- (Any additional context or information eg. in the form of error messages or screenshots.)

1- This bug did not exist before, but like 2 years ago it began appearing to me, the feature was working perfectly in the past, now it always works
2- The feature is expected to ran the command on the player I click their username in, however, when I click at their Username the console just closes.
3- The console closes when clicking on a player's username
4- It slows down the process of running commands, I have to type instead of clicking directly on the usernames.
5- I provided a video clip of the issue

https://user-images.githubusercontent.com/59706401/235512125-f869bafb-e014-41c8-a0d3-a9f3848a6946.mp4

**Comment by DaRealGandhi20** [comment]
You don't need to write the full username, you can write the first 3-4 letters of the username btw.

**Comment by FuhrerDox** [comment]
> I don't think you were ever able to click on predicted usernames, it does look like your cursor is highlighting something meaning that it's probably a text button but due to a oversight that detects whether you click anywhere on the screen to exit out of the command-line. Ringing @ccuser44...

actually it used to work like 2 years ago, I'm pretty sure when I click in their username it inserts all the username, it was to make running command in multiple people easier

**Comment by FuhrerDox** [comment]
> You don't need to write the full username, you can write the first 3-4 letters of the username btw.

true but trust me when there are like +10 players in the server it's easier to click than typing the first letters, also some people might have the same letters in the prefix of a word

**Comment by Dimenpsyonal** [comment]
Looking into this

**Comment by WaviestBalloon** [comment]
Epix janitor

**Comment by Dimenpsyonal** [comment]
What

**Comment by Dimenpsyonal** [comment]
According to my research, this still works. Problem is that the console closes when it is "unfocused" and for some reason, clicking on the console is unfocusing it??
