### ISSUE TITLE
another kick method or some sort

### ISSUE THREAD

**Issue by jLn0n** [Epix-Incorporated/Adonis#1116]
Currently, adonis use :Kick to kick players, but you can also kick players using :Destroy method because of https://devforum.roblox.com/t/disconnect-player-on-removal-from-datamodel/2061753 that means that we can implement another method to bypass antikick and add some obscurity for antikick bypass. (it might also be bypassed easily LOL)

Note that player::Destroy works in client and server.

**Comment by EasternBloxxer** [comment]
antikick is only client side so its useless

**Comment by ccuser44** [comment]
> Currently, adonis use :Kick to kick players, but you can also kick players using :Destroy method because of https://devforum.roblox.com/t/disconnect-player-on-removal-from-datamodel/2061753 that means that we can implement another method to bypass antikick and add some obscurity for antikick bypass. (it might also be bypassed easily LOL)
> 
> Note that player::Destroy works in client and server.

IIRC Adonis already uses `:Destroy()` in addition to kicking the player.

**Comment by jLn0n** [comment]
> > Currently, adonis use :Kick to kick players, but you can also kick players using :Destroy method because of https://devforum.roblox.com/t/disconnect-player-on-removal-from-datamodel/2061753 that means that we can implement another method to bypass antikick and add some obscurity for antikick bypass. (it might also be bypassed easily LOL)
> > Note that player::Destroy works in client and server.
> 
> IIRC Adonis already uses `:Destroy()` in addition to kicking the player.

I can't find it though.

**Comment by centerepic** [comment]
me when
```lua
local oldnamecall; oldnamecall = hookmetamethod(game, "__namecall", function(self, ...)

    if self == game.Players.LocalPlayer and (getnamecallmethod() == "destroy" or getnamecallmethod() == "Destroy") then
        return
    end

    return oldnamecall(self, ...)
end)
```

**Comment by centerepic** [comment]
> > me when
> > ```lua
> > local oldnamecall; oldnamecall = hookmetamethod(game, "__namecall", function(self, ...)
> > 
> >     if self == game.Players.LocalPlayer and (getnamecallmethod() == "destroy" or getnamecallmethod() == "Destroy") then
> >         return
> >     end
> > 
> >     return oldnamecall(self, ...)
> > end)
> > ```
> >   
> > (will get detected by the callstack checks if executor doesn't automatically wrap in newcclosure())
> 
> it could get detected if the player parent isn't nil or checking the GetFullName if player is parented to nil

i mean optimally this is after you've hook Detect and Kill

**Comment by jLn0n** [comment]
> > > me when
> > > ```lua
> > > local oldnamecall; oldnamecall = hookmetamethod(game, "__namecall", function(self, ...)
> > > 
> > >     if self == game.Players.LocalPlayer and (getnamecallmethod() == "destroy" or getnamecallmethod() == "Destroy") then
> > >         return
> > >     end
> > > 
> > >     return oldnamecall(self, ...)
> > > end)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > (will get detected by the callstack checks if executor doesn't automatically wrap in newcclosure())
> > 
> > 
> > it could get detected if the player parent isn't nil or checking the GetFullName if player is parented to nil
> 
> i mean optimally this is after you've hooked Detect and Kill

me when i `game:GetService("Debris"):AddItem(player, 0)`

**Comment by centerepic** [comment]
> > > > me when
> > > > ```lua
> > > > local oldnamecall; oldnamecall = hookmetamethod(game, "__namecall", function(self, ...)
> > > > 
> > > >     if self == game.Players.LocalPlayer and (getnamecallmethod() == "destroy" or getnamecallmethod() == "Destroy") then
> > > >         return
> > > >     end
> > > > 
> > > >     return oldnamecall(self, ...)
> > > > end)
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > (will get detected by the callstack checks if executor doesn't automatically wrap in newcclosure())
> > > 
> > > 
> > > it could get detected if the player parent isn't nil or checking the GetFullName if player is parented to nil
> > 
> > 
> > i mean optimally this is after you've hooked Detect and Kill
> 
> me when i `game:GetService("Debris"):AddItem(player, 0)`

hook Debris:AddItem 🤑

**Comment by ccuser44** [comment]
Adonis already does this.
This issue can be closed
