### ISSUE TITLE
Adonis Crashing My Game

### ISSUE THREAD

**Issue by SecretlyDeath0** [Epix-Incorporated/Adonis#1142]
So i added adonis to my game and it crashes the person using cmds that make a screen pop up, for example whenever you use the !help command and no one responds, it has a screen that says "Sorry no one is available to help rn" or something like that, and it crashes the game at the very last second, and it also crashes the game whenever i use the fly cmd or the ;view cmd 😭 help me please.

**Comment by Mickmick2012** [comment]
Are you using the _real_ Adonis model made by Epix Incorporated ?

**Comment by Dimenpsyonal** [comment]
Can't reproduce
