### ISSUE TITLE
The commandlogs and chatlogs does not update when you press the update button

### ISSUE THREAD

**Issue by Zsubi1** [Epix-Incorporated/Adonis#1143]
- What are the steps that lead to the bug occurring? Or, how frequently does the bug occur?
Set the textchatservice version to textchatservice then type :log or :chatlogs and when it opens just try saying something like a command and then press the reload button.
- What would be the normally expected or desired result?
When i pressed the reload or update button i thought it would update, but i did not
- What is the actual result (the bug)?
It does not update
- What is the impact of this bug?
Small to Medium
- (Any additional context or information eg. in the form of error messages or screenshots.)
I see no errors in the console
also this happens when i try to search for something on the logs the second time
![image](https://github.com/Epix-Incorporated/Adonis/assets/137436528/da04ccce-bf97-4616-b12f-4297b3d742cc)

**Comment by karl-police** [comment]
Is that fixed now?

**Comment by karl-police** [comment]
> No its still not fixed

The refresh button is the update button you're refering to, right?

Because, I press it and it works perfectly fine. Ensure you're using the latest version.

**Comment by ccuser44** [comment]
This is fixed at least in nightly

**Comment by Dimenpsyonal** [comment]
Sounds like this is fixed
