### ISSUE TITLE
Remove, or Option to disable :vomit 

### ISSUE THREAD

**Issue by Mickmick2012** [Epix-Incorporated/Adonis#1148]
- Is your feature request related to a problem? If so, please describe concisely. (Eg. "I'm always frustrated when [...]", "It's currently too difficult to [...]")
The problem is that Roblox updated their age guideline and added "Does this experience depict, reference, or encourage crude humor?"
It includes very _bad_ stuff (bodily functions), including vomitting, this sets the age to +9
- What is the solution, improvement or enhancement you'd like to see? Please describe.
Removing the :vomit command

**Comment by LiveFireExercise** [comment]
Good idea, I will be working on this

**Comment by karl-police** [comment]
@Sceleratis close :)

**Comment by LiveFireExercise** [comment]
why do you hate the other maintainers

**Comment by Mickmick2012** [comment]
you aren't supposed to close until i say it's working
