### ISSUE TITLE
Change flight toggle

### ISSUE THREAD

**Issue by 0x408** [Epix-Incorporated/Adonis#1158]
Upon using the fly command, you get the default "You are now flying. Press E to toggle flight." message. 
How do I change the toggle from E to another key, such as F? 
I believe there is no way to config this yourself as the E toggle message is hardcoded, so in which part of the code would this be changed?

Thanks :)

**Comment by ccuser44** [comment]
No, there is no way to change it unless you replace the fly script via a plugin.
