### ISSUE TITLE
Order of voting options should be randomised per client

### ISSUE THREAD

**Issue by ccuser44** [Epix-Incorporated/Adonis#1167]
- Usually when there are options people are most likely to chooce the first option no matter what it is. Eg. the order of the options affect what people choose.
- The fix to randomise the order of the options client side on things like `:vote` which will make the ordering different on all players, likely negating the issues caused by consistent ordering.

**Comment by karl-police** [comment]
@Sceleratis We need label
Commands, Enhancement and UI

I think a new command called ``:voteRandom`` with the same arguments, adding a new one to ``:vote`` may be confusing.

**Comment by LiveFireExercise** [comment]
> We need label Commands, Enhancement and UI
> 
> I think a new command called `:voteRandom` with the same arguments, adding a new one to `:vote` may be confusing.

why do you ping sceleratis on eevrything

**Comment by LiveFireExercise** [comment]
ping another dead maintainer for a label smh

**Comment by karl-police** [comment]
> ping another dead maintainer for a label smh

@Expertcoderz come back 😭

**Comment by karl-police** [comment]
there's also

@joritochip

**Comment by Dimenpsyonal** [comment]
wow epic
