### ISSUE TITLE
Command bar not opening

### ISSUE THREAD

**Issue by ForgottenNJ** [Epix-Incorporated/Adonis#1168]

**Comment by watameln** [comment]
![image](https://github.com/Epix-Incorporated/Adonis/assets/90981615/f89de047-e529-4f5e-8312-3e5c06cf244c)
hi head mod of the eastern war

**Comment by karl-police** [comment]
someone close this

**Comment by karl-police** [comment]
@Sceleratis 🙏

**Comment by LiveFireExercise** [comment]
what did i just say
https://github.com/Epix-Incorporated/Adonis/pull/1178?notification_referrer_id=NT_kwDOA9DCTrM3MjI0MzM2NzM0OjY0MDEyODc4#issuecomment-1657179338

**Comment by Dimenpsyonal** [comment]
If command bar isn't opening that's either because settings.console is disabled or you have a weird keybind set to open it. Hope this helps
