### ISSUE TITLE
F3x Crashes Players & Servers

### ISSUE THREAD

**Issue by watameln** [Epix-Incorporated/Adonis#1171]
- What are the steps that lead to the bug occurring? Or, how frequently does the bug occur?
Each time we use f3x command
- What would be the normally expected or desired result?
f3x
- What is the actual result (the bug)?
crash
- What is the impact of this bug?
no f3x
- (Any additional context or information eg. in the form of error messages or screenshots.)
cats

**Comment by watameln** [comment]
i agreee

**Comment by karl-police** [comment]
> * What are the steps that lead to the bug occurring? Or, how frequently does the bug occur?
>   Each time we use f3x command
> * What would be the normally expected or desired result?
>   f3x
> * What is the actual result (the bug)?
>   crash
> * What is the impact of this bug?
>   no f3x
> * (Any additional context or information eg. in the form of error messages or screenshots.)
>   cats

Can't reproduce this. Where does this occur, maybe something specific on your end causes the crash.

**Comment by Dimenpsyonal** [comment]
Can't repro
