### ISSUE TITLE
CustomRank help

### ISSUE THREAD

**Issue by josh478905** [Epix-Incorporated/Adonis#1182]
https://vimeo.com/850706654

I recorded me adding a custom, rank in setting,But it did not show up.

**Comment by xJustBen** [comment]
I think you missed a bracket

**Comment by karl-police** [comment]
Cannot reproduce.

Even tried it on this: https://www.roblox.com/library/7510622625/Adonis-Admin-Loader-Epix-Incorporated

It works for me.
