### ISSUE TITLE
Script timeout: exhausted allowed execution time

### ISSUE THREAD

**Issue by HakFX** [Epix-Incorporated/Adonis#1185]
I'm having this error idk what it can be, any solutions?

i'm getting this just in some servers like 50% of servers or more sometimes

![image](https://github.com/Epix-Incorporated/Adonis/assets/111817596/1db0363d-e569-4805-bf29-9eb01dfc3204)

**Comment by karl-police** [comment]
I found this post https://devforum.roblox.com/t/how-to-handle-script-timeout-exhausted-allowed-execution-time/533353/6

**Comment by ccuser44** [comment]
This issue is a dublicate of #779 so this can be closed

**Comment by Dimenpsyonal** [comment]
Finally I can use the duplicate label

**Comment by Dimenpsyonal** [comment]
Excellent
