### ISSUE TITLE
attempt to index nil with "TabToType"

### ISSUE THREAD

**Issue by WalkerOfBacon** [Epix-Incorporated/Adonis#1189]
![image](https://github.com/Epix-Incorporated/Adonis/assets/50679909/feb70e3b-1638-498e-b3e4-a0b4e072af31)
![image](https://github.com/Epix-Incorporated/Adonis/assets/50679909/6723d2e3-7e88-4142-a408-b90da2eb75c5)

**Comment by WalkerOfBacon** [comment]
This happens when you just join the game

**Comment by NoobBucket** [comment]
what's the tab variable you're passing to Logs.TabToType()?

**Comment by Expertcoderz** [comment]
Does this happen in the normal release MainModule or just the nightly?

**Comment by WalkerOfBacon** [comment]
> Does this happen in the normal release MainModule or just the nightly?

It happens in nightly

**Comment by karl-police** [comment]
> > Does this happen in the normal release MainModule or just the nightly?
> 
> It happens in nightly

does it still happen?

just by joining the game? did you modify anything?

which settings did you use, the griefed one or the old one?

**Comment by karl-police** [comment]
I emulated the issue.
![image](https://github.com/Epix-Incorporated/Adonis/assets/12023782/e8644e83-32f4-4db4-97c9-86dd7f0bb650)

**Comment by WalkerOfBacon** [comment]
> Do you have any custom plugins installed?

I havent checked but im pretty sure no
And if I do it's most likely a custom command

**Comment by karl-police** [comment]
> > Do you have any custom plugins installed?
> 
> I havent checked but im pretty sure no And if I do it's most likely a custom command

Are there any warnings in the console?

**Comment by karl-police** [comment]
@Expertcoderz Issue occurs when a TrackService fails to run a task but Logs didn't initialize.

**Comment by karl-police** [comment]
So basically @Expertcoderz 
https://github.com/Epix-Incorporated/Adonis/blob/849d4d8c167fbc92093f8254fa8a9d858bbeeebf/MainModule/Server/Core/Logs.lua#L96C4-L96C63


Logs. is nil
