### ISSUE TITLE
If a Module fails to load, Logs will try to log it as loaded but fail

### ISSUE THREAD

**Issue by karl-police** [Epix-Incorporated/Adonis#1197]
Continuation of https://github.com/Epix-Incorporated/Adonis/issues/1189

basically, it's not about that the issue is still present.
It's about that it can still happen.

**This is not important at all, but worth looking into, in the future.**

So basically @Expertcoderz 
https://github.com/Epix-Incorporated/Adonis/blob/849d4d8c167fbc92093f8254fa8a9d858bbeeebf/MainModule/Server/Core/Logs.lua#L96

``Logs`` is nil
it's not always nil

``server.Logs`` however doesn't seem to cause this, but what are we actually changing?

this line exists as well
https://github.com/Epix-Incorporated/Adonis/blob/849d4d8c167fbc92093f8254fa8a9d858bbeeebf/MainModule/Server/Core/Logs.lua#L77

``server.Logs`` was put back in the past https://github.com/Epix-Incorporated/Adonis/commit/31a10e1d7eaef1490900b5a8f171806f8ad41acf

however, what's actually even triggering this issue in the first place, is this:

https://github.com/Epix-Incorporated/Adonis/blob/849d4d8c167fbc92093f8254fa8a9d858bbeeebf/MainModule/Server/Server.lua#L236-L241

This is being called when this fails
https://github.com/Epix-Incorporated/Adonis/blob/849d4d8c167fbc92093f8254fa8a9d858bbeeebf/MainModule/Server/Server.lua#L206-L212

a ``TrackTask``, and if it fails the module also failed to load, so the Log doesn't even make sense. The "Loaded Module:" thing, is not placed at the right place. I think commenting it out for now until someone finds out where it belongs to is a good approach.

The "Loaded Module:" thing is something very old that was just left there.

**Comment by ccuser44** [comment]
I think this got fixed by moo

**Comment by karl-police** [comment]
> I think this got fixed by moo

oooo

do you have their changes link, I wanna see how they changed it, cuz I was thinking how it could be changed at that time

**Comment by ccuser44** [comment]
@Dimenpsyonal this is already fixed
