### ISSUE TITLE
How do I unban people from my game? With adonis admin

### ISSUE THREAD

**Issue by TheAwsomKid90** [Epix-Incorporated/Adonis#1219]
Alright so someone raided my roblox game now people are banned everytime I try to unban them and then rejoi to check bans are still there and wont stop.

**Comment by WalkerOfBacon** [comment]
:unban <user>

However unbanning the user wont work half (or most) of the time

**Comment by WalkerOfBacon** [comment]
:unban <user>

However unbanning the user wont work half (or most) of the time

**Comment by TheAwsomKid90** [comment]
I have found out how to remove everyone from my bans that was falsely banned by changing the datastore key thank you for your help or with trying to help.

**Comment by WalkerOfBacon** [comment]
You could try :cleardata and it should unban them that way (however it will also clear any data like aliases, keybinds, and more)

**Comment by WalkerOfBacon** [comment]
> I have found out how to remove everyone from my bans that was falsely banned by changing the datastore key thank you for your help or with trying to help.

Alright

**Comment by TheAwsomKid90** [comment]
> You could try :cleardata and it should unban them that way (however it will also clear any data like aliases, keybinds, and more)

I tried doing that but would not work.
