### ISSUE TITLE
Disable !buyitem by default

### ISSUE THREAD

**Issue by RadiantUwU** [Epix-Incorporated/Adonis#1220]
PLEASE just do it, one of my friends just lost 15k robux worth of UGC due to this.

**Comment by RadiantUwU** [comment]
Do it ASAP, please message me if i can do the pull request myself.

**Comment by WalkerOfBacon** [comment]
I'd rather make a pull request for that reason but this works too

**Comment by RadiantUwU** [comment]
Someone used !buyitem and the limited ugc id and they just took it

**Comment by watameln** [comment]
please dont fix this im abusing this

**Comment by WalkerOfBacon** [comment]
> please dont fix this im abusing this 

bypass it then lol

**Comment by LiveFireExercise** [comment]
> > please dont fix this im abusing this
> 
> The AUDACITY

my fav sound editing app

**Comment by EasternBloxxer** [comment]
this sounds more of a skill related

**Comment by RadiantUwU** [comment]
> this sounds more of a skill related 

????? Just patch a vulnerability so other games don't have to suffer?

**Comment by moo1210** [comment]
> please dont fix this im abusing this

(real)
