### ISSUE TITLE
cats

### ISSUE THREAD

**Issue by watameln** [Epix-Incorporated/Adonis#1222]
cat theme or just cats or something idk
| Header | Header | Header | Header | Header |
|--------|--------|--------|--------|--------|
| Cell | Cell | Cell | Cell | Cell |
| Cell | Cell | Cell | Cell | Cell |
| Cell | Cell | Cell | Cell | Cell |
| Cell | Cell | Cell | Cell | Cell |
| Cell | Cell | Cell | Cell | Cell |

**Comment by Speeder323** [comment]
clearly you should have called this theme "nyadonis"

**Comment by MakeSureDudeDies** [comment]
> clearly you should have called this theme "nyadonis"

x3donis

**Comment by hefahi** [comment]
https://github.com/Epix-Incorporated/Adonis/issues/1222#issuecomment-1722604240

**Comment by psaux01** [comment]
> Cell

2293709435

**Comment by psaux01** [comment]
Y

**Comment by Dimenpsyonal** [comment]
If you want a cats theme make it yourself 😼
