### ISSUE TITLE
Having CharacterAutoLoads set to false can break the command bar

### ISSUE THREAD

**Issue by Sedkoro49** [Epix-Incorporated/Adonis#1225]
CharacterAutoLoads is set to false in my game, and this causes problems with the command bar. When the player opens Adonis' command bar, two command bars appear. Both can be used to execute commands, but when the player gets rid of them, they don't bring back the chat window or default player list. The problem of two command bars persists until the player respawns. Rejoining when CharacterAutoLoads is set to true does not seem to fix the issue. The most I can say about other setups is their results have been inconsistent), making it impossible for me to pin down more patterns.

In case it's relevant: While I was studying the issue in Studio, I toggled CharacterAutoLoads and "Remote [event/function] invocation queue exhausted" errors suddenly started appearing. Unfortunately, I don't remember A) if I set CharacterAutoLoads to true or false, or B) if the errors were talking about RemoteEvents or RemoteFunctions. I was not able to determine how to make those errors appear again. Adonis never produced any other errors or related warnings in my testing.

Factors in testing:
   Was CharacterAutoLoads true or false on server startup?
   Was CharacterAutoLoads true or false when the player rejoined/respawned?
   Was CharacterAutoLoads true or false when Adonis started?
   Had the player spawned in already?
   Was the player already spawned in when Adonis started?
   
   I conducted testing in my game (in live servers and Studio) and a new baseplate (in Studio); my results for some setups were inconsistent between the two games.

**Comment by moo1210** [comment]
> In case it's relevant: While I was studying the issue in Studio, I toggled CharacterAutoLoads and "Remote [event/function] invocation queue exhausted" errors suddenly started appearing. Unfortunately, I don't remember A) if I set CharacterAutoLoads to true or false, or B) if the errors were talking about RemoteEvents or RemoteFunctions. I was not able to determine how to make those errors appear again. Adonis never produced any other errors or related warnings in my testing.

Yep, those remote invocation issues are fixed in #1216, I'll look into this issue for that PR later today as well.

**Comment by LiveFireExercise** [comment]
Excellent, thx moo
