### ISSUE TITLE
Have !buyitem Command Disabled By Default

### ISSUE THREAD

**Issue by LoadingL0n3ly** [Epix-Incorporated/Adonis#1232]
Exactly what the request says, I recently found out (the hard way) that the !buyitem command is enabled for standard players and runs the PurchasePrompt method from server, which can be **destructive** when the game is giving out Free UGC, as the command effectively bypasses any criteria setup by developers.

This is by no means a fault of the Epic Incorporated, but would nonetheless prevent unsuspecting developers from having to realize that their item's stock has evaporated instantly due to the otherwise rarely used command being enabled by defualt.

**Comment by LiveFireExercise** [comment]
It is disabled by default in the already, however the model hasn't been updated to match the github in some time

**Comment by JakeyWasTaken** [comment]
Add skibidi toilet command

**Comment by WalkerOfBacon** [comment]
> Add skibidi toilet command

no

**Comment by LoadingL0n3ly** [comment]
Oh, that makes sense as I had used the model because I needed to remove the verbose output generated by the main module (I didn't want my error reports being spammed with warnings telling me that Adonis admin had started up).

**Comment by ccuser44** [comment]
This is done.Can be closed.
