### ISSUE TITLE
`:creeper` command doesn't work with non-default player sizes

### ISSUE THREAD

**Issue by ccuser44** [Epix-Incorporated/Adonis#1249]
### Version channel

Nightly

### What part of Adonis is this related to?

Command

### What happened?

`:creeper` command doesn't work with non-default player sizes or shapes

![image](https://github.com/Epix-Incorporated/Adonis/assets/68124053/e38b3364-1b12-4f61-a08e-8404426a8002)
![image](https://github.com/Epix-Incorporated/Adonis/assets/68124053/71bc133d-9642-43d9-81c8-5c2f8c08c1fe)

### Relevant log output

```shell
N/A
```

**Comment by Dimenpsyonal** [comment]
Creeper? Aw man
