### ISSUE TITLE
Problem saving Admin

### ISSUE THREAD

**Issue by dorhdr** [Epix-Incorporated/Adonis#1262]
### Version channel

Nightly

### What part of Adonis is this related to?

Command

### What happened?

Adonis simply fails to save players in a position or remove them from positions. (`:admins`). For example, I'm going to add a friend to the list: `:setrank` or `:unadmin`.

The notification appears saying that it has been saved or removed, but the error appears in the Console and neither saves nor removes.

The problem also occurs with any command that adds a player to `:admins`.

I've removed all my plugins to test and the error persists. I've also tested with the latest version. `Adonis_Nightly_2023-11-11_master_3d04710cfccd2b5e0280354928cec8f3b64464e3`

https://github.com/Epix-Incorporated/Adonis/blob/3d04710cfccd2b5e0280354928cec8f3b64464e3/MainModule/Server/Core/Core.lua#L1018

![Screenshot_8](https://github.com/Epix-Incorporated/Adonis/assets/33329672/4b2c96e3-7b31-4f5d-a1c2-4d78d61b6c65)

### Relevant log output

```shell
ServerScriptService.Adonis.MainModule.Server.Core.Core:1018: attempt to index nil with 'Type'
ServerScriptService.Adonis.MainModule.Server.Shared.Service:108
ServerScriptService.Adonis.MainModule.Server.Core.Core:1018 function DoSave
ServerScriptService.Adonis.MainModule.Server.Shared.Service:126 function taskFunc
```

**Comment by Dimenpsyonal** [comment]
How typical

**Comment by fxeP1** [comment]
This issue should be fixed on this PR once merged: https://github.com/Epix-Incorporated/Adonis/pull/1264. If you're looking to just use it ASAP then download the artifact here: https://github.com/Epix-Incorporated/Adonis/actions/runs/6835425801

**Comment by dorhdr** [comment]
Thank you!
