### ISSUE TITLE
[Bug]: Nightly is not up to date.

### ISSUE THREAD

**Issue by ccuser44** [Epix-Incorporated/Adonis#1268]
The nightly module is not up to date.

Also we probably should not release v240 just yet because master contains a lot of bug fixes and stuff that isn't in release.

**Comment by Dimenpsyonal** [comment]
Yeah I wonder whose fault that is...

**Comment by WalkerOfBacon** [comment]
I wonder

**Comment by Dimenpsyonal** [comment]
Isn't v240 fine though. Like it's nightly that isn't fine

**Comment by ccuser44** [comment]
> Isn't v240 fine though. Like it's nightly that isn't fine

Nightly seems to work for me


There are bugs in v240 that arent in nightly

**Comment by Dimenpsyonal** [comment]
Fiiine... No more v240 for you guys

**Comment by Dimenpsyonal** [comment]
Good news; this gonna be fixed when sceleratis fixes the server today

**Comment by moo1210** [comment]
Unfortunately, we have failed to fix the server and release v240.
![image](https://github.com/Epix-Incorporated/Adonis/assets/27241938/198dc8e6-9b9d-4d21-bde5-311fa6881e76)
![image](https://github.com/Epix-Incorporated/Adonis/assets/27241938/fd060623-7f14-4927-bde8-13462a67a4ba)

> Also we probably should not release v240 just yet because master contains a lot of bug fixes and stuff that isn't in release.

Yeah like this loader bug fix:
![image](https://github.com/Epix-Incorporated/Adonis/assets/27241938/428d53a0-9d34-437b-9e2c-854284d0aee7)
(+ all the broken commands)

**Comment by WalkerOfBacon** [comment]
found another error
![image](https://github.com/Epix-Incorporated/Adonis/assets/50679909/beaead15-9c4d-494d-9965-bacd8154a44b)

**Comment by Dimenpsyonal** [comment]
Another error where

**Comment by WalkerOfBacon** [comment]
> Another error where

I wonder where

**Comment by Dimenpsyonal** [comment]
Nightly on roblox or current nightly

**Comment by WalkerOfBacon** [comment]
nightly

**Comment by WalkerOfBacon** [comment]
latest one

**Comment by Dimenpsyonal** [comment]
As always I blame ccuser

**Comment by Dimenpsyonal** [comment]
> Unfortunately, we have failed to fix the server and release v240.

@moo1210 dw sceleratis will DEFINITLEY do that today

**Comment by spearmintroblox** [comment]
It will be updated, stop your yapping

**Comment by ccuser44** [comment]
> found another error ![image](https://user-images.githubusercontent.com/50679909/282935323-beaead15-9c4d-494d-9965-bacd8154a44b.png)

You have invalid commands if you get that
One of your plugins sets a function to `server.Commands`

**Comment by WalkerOfBacon** [comment]
> You have invalid commands if you get that
> One of your plugins sets a function to `server.Commands`

Im not using any plugins
+ this error appears when I switch the chat version to the new one

**Comment by ccuser44** [comment]
> > You have invalid commands if you get that
> > One of your plugins sets a function to `server.Commands`
> 
> Im not using any plugins
> 
> * this error appears when I switch the chat version to the new one

It certainly doesn't appear for me. How are you exactly using your nightly module? Did you build the latest nightly from github?

**Comment by WalkerOfBacon** [comment]
> It certainly doesn't appear for me. How are you exactly using your nightly module? Did you build the latest nightly from github?

Yes

**Comment by ccuser44** [comment]
> > It certainly doesn't appear for me. How are you exactly using your nightly module? Did you build the latest nightly from github?
> 
> Yes

Compile https://github.com/Epix-Incorporated/Adonis/archive/refs/heads/master.zip with rojo and then show a screenshot of the error.
It doesn't happen with me or anyone else who uses nightly

**Comment by WalkerOfBacon** [comment]
Ill try that when I get the chance

**Comment by WalkerOfBacon** [comment]
@ccuser44 I compiled adonis with rojo but its not inserting into studio
Also the same error shows up in-game, not in my console

**Comment by ccuser44** [comment]
> @ccuser44 I compiled adonis with rojo but its not inserting into studio

Compile to rbxl

**Comment by Dimenpsyonal** [comment]
Upload server is fixed so issue resolved
