### ISSUE TITLE
settings.OnStartup no longer executes command

### ISSUE THREAD

**Issue by Vlocks9090** [Epix-Incorporated/Adonis#1306]
### Version channel

Stable (Default)

### What part of Adonis is this related to?

Loader/Settings

### What happened?

With the new 240 update, the settings.OnStartup command no longer execute themselves when a new server opens.
![image](https://github.com/Epix-Incorporated/Adonis/assets/84682290/c50e9669-f13d-4fe3-9b67-3b2e6577db08)

**Comment by Dimenpsyonal** [comment]
Weird

**Comment by Dimenpsyonal** [comment]
Problem may be in Admin.lua. Do you recieve any :scriptlogs or print statements
```
		--// Run OnStartup Commands
		for i,v in Settings.OnStartup do
			print(`Running startup command {v}`)
			TrackTask(`Thread: Startup_Cmd: {v}`, Admin.RunCommand, false, v)
			AddLog("Script", {
				Text = `Startup: Executed {v}`;
				Desc = `Executed startup command; {v}`;
			})
		end
```

**Comment by Vlocks9090** [comment]
Still does not work I'm afraid. Says it is executed but setmsg does not appear.
![image](https://github.com/Epix-Incorporated/Adonis/assets/84682290/c59f26b9-ae9d-4d15-b8a8-fe31b9586f00)

**Comment by Vlocks9090** [comment]
![image](https://github.com/Epix-Incorporated/Adonis/assets/84682290/8ee2f3ad-0d3f-4239-9bc9-c6640ef62a22)
![image](https://github.com/Epix-Incorporated/Adonis/assets/84682290/aef74c95-54c8-435c-8125-04efc033dd16)
From the console.

**Comment by GGshor** [comment]
> ![image](https://private-user-images.githubusercontent.com/84682290/294674253-8ee2f3ad-0d3f-4239-9bc9-c6640ef62a22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NDEwNTksIm5iZiI6MTcwNDU0MDc1OSwicGF0aCI6Ii84NDY4MjI5MC8yOTQ2NzQyNTMtOGVlMmYzYWQtMGQzZi00MjM5LTliYzktYzY2NDBlZjYyYTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDExMzIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkN2U2YWQ2YzFkNTVmZTk0YzlmOGMwMmIxMmFjNTFhYjgyNzBjNTMwMDhiZTk1ZWU3NjJiZjI3MjI5MDE4ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yal6VMGQo26wUtmlzVFtdh5ayTp7qmu297-H6TFkxl8) ![image](https://private-user-images.githubusercontent.com/84682290/294674315-aef74c95-54c8-435c-8125-04efc033dd16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NDEwNTksIm5iZiI6MTcwNDU0MDc1OSwicGF0aCI6Ii84NDY4MjI5MC8yOTQ2NzQzMTUtYWVmNzRjOTUtNTRjOC00MzVjLTgxMjUtMDRlZmMwMzNkZDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDExMzIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1N2RiY2FiMDNiYTRmNjZhZjljM2RmY2FkZDk4YjFlZDQ1YjUwNjFlMjhiMjgzMTEwOGY1MGZkMjgyZDkwZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q4PN9fw5-3ieeM4jEYrTxUzbofNrX1CePhYH0A4GvVE) From the console.

When I enable nightly mode it works for me, can you try to enable it in your game to see if this solves the problem for you?

_**Do note that this enables the unstable version of Adonis, so you should only enable this temporarily**_

You can enable it by going to the Adonis model, the loader folder, and then opening the loader script found here:
![image](https://github.com/Epix-Incorporated/Adonis/assets/73340248/9a745564-36d9-4562-8534-d21d36016046)

And turning the `false` on line 91 to `true`
![image](https://github.com/Epix-Incorporated/Adonis/assets/73340248/965505a7-1557-42d1-b240-2008d497b66a)

**Comment by Vlocks9090** [comment]
Yep, it is fixed in the nightly when i enable it

**Comment by Dimenpsyonal** [comment]
v241 has released which contains this fix so hopefully this is fixed now
