### ISSUE TITLE
Votekick command for Players

### ISSUE THREAD

**Issue by Pludam** [Epix-Incorporated/Adonis#1311]
### What part of Adonis is this related to?

Command

### What are you suggesting?

Add an Votekick system to Adonis. An good example would be the Votekick system in [Realistic Boiling Water Reactor Simulator](https://www.roblox.com/games/11765852158/V1-4-2-Realistic-Boiling-Water-Reactor-Simulator) on Roblox.

**Comment by Pludam** [comment]
I would add it on my own but i don´t know how to script it sadly.

**Comment by EasternBloxxer** [comment]
No. Votekick systems are stupid. Even in the (very shit) example provided in the suggestion the votekick system has been abused many times

**Comment by Pludam** [comment]
The example is the only good votekick system I know and yes there are some complaints even in the community of the game I forgot about so I’m closing this

**Comment by coasterteam** [comment]
could still write a plugin for those who want to have a votekick system

**Comment by Dimenpsyonal** [comment]
yea a plugin sounds more suitable for the niche nature of votekicks
