### ISSUE TITLE
ALL THE BANS ON MY GAME GOT RESETTED, WHY IS THAT???

### ISSUE THREAD

**Issue by perrapig** [Epix-Incorporated/Adonis#1333]
### Version channel

Stable (Default)

### What part of Adonis is this related to?

Command

### What happened?

out of thin air all the people on my game are unbanned, why is that? literally years of banned people and now they are all poof now all unbanned, please fix this.

### Relevant log output

```shell
out of thin air all the people on my game are unbanned, why is that? literally years of banned people and now they are all poof now all unbanned, please fix this.
```

**Comment by PurpleCreativity** [comment]
that's a nice relevant log output

**Comment by kaiserandaxl** [comment]
@perrapig By chance is your DataStoreName and Key the same as before?

**Comment by kaiserandaxl** [comment]
And I'd also love to see version of main module run `:changelog` and version of loader

**Comment by perrapig** [comment]
im sorry the mayus were enabled, let me try get the things you asking for sorry

**Comment by perrapig** [comment]
![image](https://github.com/Epix-Incorporated/Adonis/assets/156142583/302f851f-ea70-42d5-a2f5-dfcbc3873f80)
is this what you asking for? and also i've never checked the data stores names or anything like that, i just remember banning and thats it, but im not a programmer so i don't really know what happened, i haven't touched any setting myself.

**Comment by Dimenpsyonal** [comment]
No clue why this would have happened

**Comment by P3tray** [comment]
what your describing is impossible without someone touching the settings file

you are the first person ever to experience this problem

**Comment by P3tray** [comment]
L
