### ISSUE TITLE
Volume command dont work correctly

### ISSUE THREAD

**Issue by SleepyDaniel** [Epix-Incorporated/Adonis#1354]
### Version channel

Stable (Default)

### What part of Adonis is this related to?

Command

### What happened?

Cant use numbers below 1 (like 0.9, 0.4) when using :volume command. Never had this issue.

### Relevant log output

```shell
required_asset_7510592873.MainModule.Server.Core.Process:380: invalid argument #1 to 'match' (string expected, got nil)
```

**Comment by SuperCater** [comment]
![image](https://github.com/Epix-Incorporated/Adonis/assets/84566931/531ec105-19ba-40aa-b6bf-c3d2454f6101)
cause seems to be the modification of trim function in #1326 

Not experienced with string patterns so i cant really provide anymore info beyond that

**Comment by Dimenpsyonal** [comment]
Fixed
