### ISSUE TITLE
Vote command sends numbers the wrong way round.

### ISSUE THREAD

**Issue by Vlocks9090** [Epix-Incorporated/Adonis#1376]
### Version channel

Stable (Default)

### What part of Adonis is this related to?

Command

### What happened?

![image](https://github.com/Epix-Incorporated/Adonis/assets/84682290/15765a7a-d1bd-4f40-92e3-4e36467db3d1)
E.G. :vote 1,2,3,4,5 How much did you enjoy your flight as staff today. Sends the numbers in the wrong order based of the command (would be the same if these were words). This has been a problem for a few weeks but didn't want to bring it up in case if it would be fixed.

**Comment by Dimenpsyonal** [comment]
Yeah we anticipated this, use the :ordervote command

**Comment by Vlocks9090** [comment]
Great thank you .Sent from my iPhoneOn 21 Jan 2024, at 6:28 pm, Dimenpsyonal ***@***.***> wrote:﻿
Yeah we anticipated this, use the :ordervote command

**Comment by P3tray** [comment]
hello

i would like to order one vote please

thank you
