### ISSUE TITLE
UI Inheritance

### ISSUE THREAD

**Issue by ccuser44** [Epix-Incorporated/Adonis#1390]
### What part of Adonis is this related to?

User Interface

### What are you suggesting?

Currently the UI code for everything is dublicated for every single theme from the default theme for no reason. This makes updating the UI a pain as every single theme needsto be updated and they often lag behind in critical updates and often break.

Hence inheriting UI elements from other themes should be added.
There should be a general apply UI mask thing which would apply to all UI elements (therefor only requiring one script in the best case schenario).
Of course overriding UI elements totally should be an option as well in the case where you would wan't different functioanlity for a different theme to a specific UI element.

**Comment by ccuser44** [comment]
The two worst examples of this are
- https://github.com/Epix-Incorporated/Adonis/blob/master/MainModule/Client/UI/Aero.rbxmx
- https://github.com/Epix-Incorporated/Adonis/blob/master/MainModule/Client/UI/Windows%20XP.rbxmx

Also the https://github.com/Epix-Incorporated/Adonis/blob/master/MainModule/Client/UI/Mobilius.rbxmx theme should just be removed totally

**Comment by Dimenpsyonal** [comment]
Themes folderised, hopefully this helps with spotting obvious flaws like setfenv

**Comment by ccuser44** [comment]
This helps quite a lot but we still need some system which would be better than the current default theme setup

Applying transformations to the UI elements instead of dublicating the code would be a lot better
Most of the themes could only be reduced to 1 modulescript which would automatically be run over the defaulttheme instance implementing the desired changes

**Comment by ccuser44** [comment]
Somewhat related pull: #1394

**Comment by P3tray** [comment]
Worth mentioning UI (Theme) inheritance exists already via the Base_Theme StringValue and Default theme setting. The post title appears to be misleading.

**Comment by P3tray** [comment]
The system could be enhanced to inherit code folders for non-modulescript UI's if I didn't already make it do that. Sadly, beyond that I'd leave all the other UI stuff to Adonis 2 as the current system is too massive.

**Comment by ccuser44** [comment]
> Worth mentioning UI (Theme) inheritance exists already via the Base_Theme StringValue and Default theme setting. The post title appears to be misleading.

Right, I wasn't originally aware of this

However to me it not sufficient

The code of UI should ideally be copied from the base theme instead of existing on both themes

My solution to this was the UI mask thing which is basically a hook to the disolay function that changes a few properties before the UI is displayed

**Comment by kaiserandaxl** [comment]
That's called modifying module codes.

**Comment by kaiserandaxl** [comment]
There are modules for certain things that just inherit and modify the inherited code.

**Comment by simulified** [comment]
There is a problem
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 1000; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```
