### ISSUE TITLE
One of my models in the insert list is not showing

### ISSUE THREAD

**Issue by DionBlox1** [Epix-Incorporated/Adonis#1395]
### Version channel

Stable (Default)

### Loader version

240

### What part of Adonis is this related to?

Loader/Settings

### What happened?

One of my models in the insert list is not showing. I tried adding another model to fix it but did not work.
Images: (IDs have been hidden)
![Screenshot 2024-02-02 232429](https://github.com/Epix-Incorporated/Adonis/assets/90649001/c43ce628-8f90-45e0-8b17-99135655344d)
![Screenshot 2024-02-02 232536](https://github.com/Epix-Incorporated/Adonis/assets/90649001/6178a0a6-29b6-4a33-8df6-e05049c04b96)

**Comment by kaiserandaxl** [comment]
@DionBlox1  check if the ID is correct

**Comment by DionBlox1** [comment]
It is correct.
![Screenshot 2024-02-03 110732](https://github.com/Epix-Incorporated/Adonis/assets/90649001/6bce25f5-4070-42ed-b4a1-ed3791bbff54)
![Screenshot 2024-02-03 110945](https://github.com/Epix-Incorporated/Adonis/assets/90649001/5f8228b5-445d-4726-961c-3a53bdc2a3b9)

**Comment by ccuser44** [comment]
> It is correct. ![image](https://private-user-images.githubusercontent.com/90649001/302031630-2dc73cd1-c56f-4fac-99c6-086555395806.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTkwMjQsIm5iZiI6MTcwNjk1ODcyNCwicGF0aCI6Ii85MDY0OTAwMS8zMDIwMzE2MzAtMmRjNzNjZDEtYzU2Zi00ZmFjLTk5YzYtMDg2NTU1Mzk1ODA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDExMTIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YjlmOGY2YWM5OGNhNzZkOTQ2NjAzODNhM2M3MzU5OTNiN2I3NTBhMTY1ZTBlNDcxYTlhNjU0YWIzMjM3ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4F26uEH1sXk4rU6cMam5X4EqenKrJ8F2NKyX_ohPeSg) ![Screenshot 2024-02-03 110945](https://private-user-images.githubusercontent.com/90649001/302031573-5f8228b5-445d-4726-961c-3a53bdc2a3b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTkwMjQsIm5iZiI6MTcwNjk1ODcyNCwicGF0aCI6Ii85MDY0OTAwMS8zMDIwMzE1NzMtNWY4MjI4YjUtNDQ1ZC00NzI2LTk2MWMtM2E1M2JkYzJhM2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDExMTIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MDM5YjZmY2Y1NjU5YzhmNjE2OWUyNjZmYWNlNDI0ZjE0ZjUzMTNiZWEyNTFmYjRiZDg1ZmYyNTQ4NmViMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1D0aOmYpIQus5-jj6hm-kJ9MV2xEJD-gLjnBmADlOrY)

Can you send a full screenshot of the insertlist settings part and blank out the IDs

**Comment by DionBlox1** [comment]
Ones that is applied:
![image](https://github.com/Epix-Incorporated/Adonis/assets/90649001/babedbed-0157-4e60-9bc3-4895a2b0964b)
Ones that are not applied: (ignore tug its applied. and patch to atempt fix it)
![image](https://github.com/Epix-Incorporated/Adonis/assets/90649001/83ec9c9b-f48e-4573-8b48-13c1d4c11667)

**Comment by ccuser44** [comment]
> Ones that is applied: ![image](https://private-user-images.githubusercontent.com/90649001/302031985-babedbed-0157-4e60-9bc3-4895a2b0964b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTk1MDgsIm5iZiI6MTcwNjk1OTIwOCwicGF0aCI6Ii85MDY0OTAwMS8zMDIwMzE5ODUtYmFiZWRiZWQtMDE1Ny00ZTYwLTliYzMtNDg5NWEyYjA5NjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDExMjAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlODE2MDMxYzk3MDcwODY3ZmNmY2I2YTYwNDU4OTY4NDU1OTIzY2VhMjQxYjRlMjNkNGY1M2MwYmY4ZWQ0ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aNGOo2N62f5XOBleIEtZmDpMKdZiHpGHr5ig6K1N72Y) Ones that are not applied: (ignore tug its applied. and patch to atempt fix it) ![image](https://private-user-images.githubusercontent.com/90649001/302032010-83ec9c9b-f48e-4573-8b48-13c1d4c11667.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTk1MDgsIm5iZiI6MTcwNjk1OTIwOCwicGF0aCI6Ii85MDY0OTAwMS8zMDIwMzIwMTAtODNlYzljOWItZjQ4ZS00NTczLThiNDgtMTNjMWQ0YzExNjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDExMjAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmODQ0OTUwZmM5NjdlYzcyNWY4MzMxNDA4YTUwMjE2OWJhYjAwODZhNDA3NmVmYzc5NGRkMzM2OWMwMGUzODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ASowlRi6Qomf7SsuwftbCFW7yXteL1ycqHIYI6L_lwE)

Again you didn't post the full one, the upper screenshot shows more vehicles than the bottom one

Post the full setting starting from `settings.InsertList` and ending in the last curly brace (with IDs blanked out of course)

**Comment by DionBlox1** [comment]
Here is code  (patch is roblox ad billboard and XXX is blanked out IDs)
```
settings.InsertList = {{Name = "Buggy", ID = XXX}; {Name = "Airstairs", ID = XXX}; {Name = "7879", ID = XXX}; {Name = "Pushback", ID = XXX}; {Name = "LavTruck", ID = XXX}; {Name = "GPU", ID = XXX}; {Name = "Catter", ID = XXX}; {Name = "BagCarts", ID = XXX}; {Name = "Tug", ID = XXX}; {Name = "Fuel", ID = XXX1770}; {Name = "patch", ID = 12945612490};} 	-- List of models to appear in the :insertlist and can be inserted using ':insert <name>'	  Format: {{Name = "somemodel", ID = 1234567}; {Name = "anotherone", ID = 1243562}}
```

**Comment by ccuser44** [comment]
> Here is code (patch is roblox ad unit and XXX is blanked out IDs)
> 
> ```
> settings.InsertList = {{Name = "Buggy", ID = XXX}; {Name = "Airstairs", ID = XXX}; {Name = "7879", ID = XXX}; {Name = "Pushback", ID = XXX}; {Name = "LavTruck", ID = XXX}; {Name = "GPU", ID = XXX}; {Name = "Catter", ID = XXX}; {Name = "BagCarts", ID = XXX}; {Name = "Tug", ID = XXX}; {Name = "Fuel", ID = XXX1770}; {Name = "patch", ID = 12945612490};} 	-- List of models to appear in the :insertlist and can be inserted using ':insert <name>'	  Format: {{Name = "somemodel", ID = 1234567}; {Name = "anotherone", ID = 1243562}}
> ```

Odd, it seems to be totally correct
Can you post a screenshot of `:scriptlogs` and `:errorlogs` after you have done `:insertlist`

**Comment by DionBlox1** [comment]
![image](https://github.com/Epix-Incorporated/Adonis/assets/90649001/01baaf51-6bf1-4fbb-8f8f-e58fe0fe66b9)

**Comment by ccuser44** [comment]
The image did not show anything specific and I couldn't reproduce this issue

**Comment by DionBlox1** [comment]
Should I close this as not planned or as completed, or wait

**Comment by ccuser44** [comment]
> EDIT: It says "Argument 1 missing or nil" when i insert it (Fuel)
> ￼

Ohhhh its probably because of the ( or )

**Comment by DionBlox1** [comment]
I got a reply with the following: "Ohhhh its probably because of the ( or )" then it was deleated

**Comment by Dimenpsyonal** [comment]
What

**Comment by DionBlox1** [comment]
It works now! 
![image](https://github.com/Epix-Incorporated/Adonis/assets/90649001/f33bf764-282c-4371-921a-4350a681ae26)
