### ISSUE TITLE
Discord Webhook integration

### ISSUE THREAD

**Issue by Pludam** [Epix-Incorporated/Adonis#1398]
### What part of Adonis is this related to?

Other

### What are you suggesting?

Discord Webhook integration for warns, bans, etc. Im thinking of something like this:
![Adonis Webhook example](https://github.com/Epix-Incorporated/Adonis/assets/109984063/8d2b1b1a-3024-421a-8eaa-c69777e530cb)
I can update the current mockup if you want

**Comment by ccuser44** [comment]
Already exists https://github.com/Epix-Incorporated/Adonis-Plugins/blob/master/Server/Server-DiscordWebhookLogs.lua

**Comment by Pludam** [comment]
oh didnt see that. Thank you!
