### ISSUE TITLE
Any commands ran by "Admin.RunCommand" will target every players regardless of the argument.

### ISSUE THREAD

**Issue by cl1ents** [Epix-Incorporated/Adonis#1409]
### Version channel

Stable (Default)

### Loader version

249

### What part of Adonis is this related to?

Command

### What happened?

Whenever a command is ran through `Admin.RunCommand` gets run, the `service.GetPlayers` function will always return every player present on the server.
This is likely caused by [line 515 in the Functions script](https://github.com/Epix-Incorporated/Adonis/blob/56941974e5f805f5623a6438f9d9aea5a79f173a/MainModule/Server/Core/Functions.lua#L515) that just returns all players if the "plr" argument is nil.

The commands affected are:
- AFK
- BreakDance
- NoClip
- Noobify
- Ghostify
- Shrek
- LoopFling
- Deadlands

And probably many others (basically any commands that use Admin.RunCommand over Commands.COMMAND.Function)

**Comment by cl1ents** [comment]
A temporary but stupid fix is replacing [line 1193 in Admin.lua](https://github.com/Epix-Incorporated/Adonis/blob/56941974e5f805f5623a6438f9d9aea5a79f173a/MainModule/Server/Core/Admin.lua#L1193) by `end, false, args)`, however a better fix would be using a fake player, but to be honest I don't want to look too deep into it, as the RunCommand function doesn't seem to be used that often, and should be replaced by either `Commands.COMMAND.Function` or `Admin.RunCommandAsPlayer` in all of the concerned commands.

You can achieve the temporary fix via a plugin that replaces `Admin.RunCommand`:

```
return function(Vargs)
	Vargs.Server.Admin.RunCommand = function(coma: string, ...)
		local _, com = Admin.GetCommand(coma)
		if com then
			local cmdArgs = com.Args or com.Arguments
			local args = Admin.GetArgs(coma, #cmdArgs, ...)

			Vargs.Service.TrackTask(`Command: {coma}`, com.Function, function(err)
				warn(`Encountered an error while running a command: {coma}\n{err}\n{debug.traceback()}`)
			end, false, args) -- no idea how bad of an idea this is lol
		end
	end;
end
```

**Comment by fxeP1** [comment]
Definitely agreeing that `Admin.RunCommand` should be replaced for alternatives like `Admin.RunCommandAsPlayer` instead. For now, I've made a quick PR that resolves the issue by using `false` instead of `nil`.

A future PR that migrates over to better alternatives will probably be done for the long run.
