### ISSUE TITLE
Using !rejoin allows you to get more players than the max player count

### ISSUE THREAD

**Issue by RadiantUwU** [Epix-Incorporated/Adonis#1416]
closes #1415 

### Version channel

Stable (Default)

### What part of Adonis is this related to?

Command

### What happened?

Using !rejoin, you would've expected roblox to simply drop them in queue, however this race condition did not have one, so they just went all in.
Here are the results of what !rejoin allows you to do:
![image](https://github.com/Epix-Incorporated/Adonis/assets/69520693/52f62e54-174e-4681-afc9-8107b747433d)
![image](https://github.com/Epix-Incorporated/Adonis/assets/69520693/4f4a463c-f3b0-45d6-abb7-31ecbeaa7520)
![image](https://github.com/Epix-Incorporated/Adonis/assets/69520693/43d91af4-600f-4dca-b365-e25939bde413)

**Comment by ccuser44** [comment]
Working as intended

**Comment by P3tray** [comment]
> Is bypassing max players intended, tho

it isn't inherently doing that tho, roblos is being silly, we should not fix

**Comment by RadiantUwU** [comment]
> > Is bypassing max players intended, tho
> 
> it isn't inherently doing that tho, roblos is being silly, we should not fix

why should we not fix when i already have made the changes needed to fix it?
