### ISSUE TITLE
Attempting to message a player with the _G api returning "attempt to iterate over a nil value"

### ISSUE THREAD

**Issue by qfoxb** [Epix-Incorporated/Adonis#1460]
### Version channel

Stable (Default)

### Loader version

255

### What part of Adonis is this related to?

Command

### What happened?

I'm attempting to message a player using `_G.Adonis.Message("<message text here>", player)` and adonis is not messaging the player.

### Relevant log output

```shell
required_asset_7510592873.MainModule.Server.Core.Functions:924: attempt to iterate over a nil value
```

**Comment by SuperCater** [comment]
Thats because those arent the correct params for the Message function

The params are 
![2024-03-25-21-20-902](https://github.com/Epix-Incorporated/Adonis/assets/84566931/73572167-2779-4bfe-b916-6defb9b00887)

**Comment by qfoxb** [comment]
Is there actual documentation on this? I was just going off the hint code `_G.Adonis.Hint("Message", game.Players:GetPlayers())` and replacing hint with message assuming they were similar in arguments.

**Comment by Dimenpsyonal** [comment]
Yes, documentation is here https://github.com/Epix-Incorporated/Adonis/wiki/G-API

**Comment by P3tray** [comment]
I know its been a few years, and this is an unrelated thread, but I'm pretty sure _G.Adonis.RunCommandAsNonAdmin(command, plr, ...) doesn't work, because I made it.

**Comment by Dimenpsyonal** [comment]
So fix it.

**Comment by qfoxb** [comment]
> Yes, documentation is here https://github.com/Epix-Incorporated/Adonis/wiki/G-API

thank you for updating it

**Comment by P3tray** [comment]
> So fix it.

nuh uh
