### ISSUE TITLE
(Unity only) FormattedChangelog disables RichText after page switching

### ISSUE THREAD

**Issue by ReinoScreech** [Epix-Incorporated/Adonis#1532]
### Version channel

Stable (Default)

### Loader version

v258

### What part of Adonis is this related to?

User Interface

### What happened?

When running `:changelog` or opening the changelog window from `:info`, The changelog window works as expected (FormattedChangelog), but after switching to a different page, it no longer becomes formatted and instead shows normal text (Without RichText being enabled).

This only occurs on Unity theme.
![RobloxPlayerBeta_bnCvopuOc9](https://github.com/Epix-Incorporated/Adonis/assets/106720292/f6e57649-c335-473a-bfce-49afa0186216)

### Device

Windows

**Comment by Dimenpsyonal** [comment]
Thats weird. Thx for the report I'll investigate

**Comment by Dimenpsyonal** [comment]
Fixed in next update
