### ISSUE TITLE
Free Admin

### ISSUE THREAD

**Issue by HelloKerem** [Epix-Incorporated/Adonis#1544]
### What part of Adonis is this related to?

Loader/Settings

### What are you suggesting?

How do i add admin to everyone
in settings?
![image](https://github.com/Epix-Incorporated/Adonis/assets/98821815/fa867d11-158b-497f-84a5-6a4914aad79b)
its not work

**Comment by fhgdfhgsfh12** [comment]
try put in admin/mod/idk list:  group:anyGroupId:0,
group:anyGroupId:1...

**Comment by Dimenpsyonal** [comment]
Use https://github.com/Epix-Incorporated/Adonis-Plugins/blob/master/Server/Server-Free_Admin.lua
