### ISSUE TITLE
The ping values ​​are different.

### ISSUE THREAD

**Issue by mtmtyu** [Epix-Incorporated/Adonis#1555]
### Version channel

Stable (Default)

### What part of Adonis is this related to?

Loader/Settings

### What happened?

The ping value displayed by Adonis' !ping is different from the ping value displayed in Roblox's performance status.
I'm Japanese and I use Google Translate.

![image](https://github.com/Epix-Incorporated/Adonis/assets/81827724/3e94f125-c236-4e98-90c6-ad93ee5e9c25)

### Device

Windows

**Comment by ccuser44** [comment]
Adonises perfstats only update each 1 second so it eill always be 0-1 seconds old valye
