### ISSUE TITLE
Command bar not working for people under 900 admin level

### ISSUE THREAD

**Issue by SLFRGacha** [Epix-Incorporated/Adonis#1577]
### Version channel

Stable (Default)

### Loader version

228

### What part of Adonis is this related to?

User Interface

### What happened?

When a moderator from my game press "Quote" it dosen't open the command bar / console, it only works for people over 900 admin permissions. (there is no errors)

Thanks for helping me.

### Device

Windows

### Relevant log output

```shell
Nothing, no errors
```

**Comment by zman29er** [comment]
This might be speculation, but I have reason to believe this stemmed from a Roblox update that was pushed out today that broke the console. Everyone that has worked with Adonis so far has had this issue.

**Comment by SLFRGacha** [comment]
> This might be speculation, but I have reason to believe this stemmed from a Roblox update that was pushed out today that broke the console. Everyone that has worked with Adonis so far has had this issue.

I hope they will fix it soon my moderators needs this

**Comment by ccuser44** [comment]
It's likely that you have the `.Console_AdminsOnly` setting on. Check if the players even have admin privileges by posting a screenshot of `:Admins`.
In any case you are using a 3 year old loader so please update to the [newest version](https://www.roblox.com/library/7510622625) and see if the issue disappears. If not send a screenshot of `:scriptlogs` and `:errorlogs` and tell all the plugins you have and the modifications you have done to the settings

**Comment by ccuser44** [comment]
Already fixed in https://github.com/ccuser44/Adonis/commit/4ba0d945b45f7b151c2f441a5844a3d0b2ffb084
