### ISSUE TITLE
Command aliases no longer working after the patch

### ISSUE THREAD

**Issue by jasieleczeq** [Epix-Incorporated/Adonis#1579]
### Version channel

Stable (Default)

### What part of Adonis is this related to?

Other

### What happened?

Filling aliases with arg1 etc. no longer works, it brings up a "Missing player: No user named 'arg1' exists" error.
![image](https://github.com/user-attachments/assets/65f4af5e-9e7d-4cb8-8da5-c43f74f91eb2)
![image](https://github.com/user-attachments/assets/459e4b4a-6080-47f4-a2e7-5caa8303a2b1)

### Device

Windows

**Comment by EasternBloxxer** [comment]
Can you show me what you tried running? Like the :c player in chat

**Comment by jasieleczeq** [comment]
It keeps responding like this no matter what I type in.


https://github.com/user-attachments/assets/207419ab-484e-460b-83d9-e1180596b502

**Comment by jasieleczeq** [comment]
Forgot to mention, it was working fine until today, so has to deal with one of the newest patches.

**Comment by EasternBloxxer** [comment]
This issue will be fixed next release
![image](https://github.com/user-attachments/assets/e8d387b8-28b6-4e3b-845e-6ca56bfbff00)
