### ISSUE TITLE
Modlogs need be disabled in Studio

### ISSUE THREAD

**Issue by Dimenpsyonal** [Epix-Incorporated/Adonis#1588]
### Version channel

Nightly

### Loader version

v261

### What part of Adonis is this related to?

Command

### What happened?

Auditlogs needs to be fixed/disabled in studio as datastore is not available. Creates some annoying errors that I'd rather have removed and could create other unforseen errors

### Device

MAC

### Relevant log output

```shell
[14:12:00] :: Adonis :: You must publish this place to the web to access DataStore.
[14:12:00] :: Adonis :: CMDMODULE HeadAdmins failed to load:
```

**Comment by ccuser44** [comment]
@Dimenpsyonal This is fixed now.
