### ISSUE TITLE
Text chat commands are autocompleted to all users, including users without mod/admin

### ISSUE THREAD

**Issue by break-core** [Epix-Incorporated/Adonis#1600]
### Version channel

Stable (Default)

### Loader version

260

### What part of Adonis is this related to?

Command

### What happened?

When I type a command in the chat (if the game uses `TextChatService`), it *would* be expected that whitelisted users should only be able to see the command and not normal users without moderator/admin. However, this is not the case.

Users, even if they **aren't** whitelisted, are able to see **all** commands in Adonis in chat by just typing /. This is very annoying for normal users, because they may want to type something like `/e dance2` but they are unable to because of the number of commands that show up in autocomplete.

## Why does this happen?
I've actually tracked the issue down, and I've found the source of the issue:

When text chat commands are created by Adonis, they are created without *ever* touching anything related to [AutocompleteVisible](https://robloxapi.github.io/ref/class/TextChatCommand.html#member-AutocompleteVisible). Due to this, the commands have AutocompleteVisible turned on **by default**. This means that Adonis is not checking whether a user should be seeing these commands in the chat autocomplete.

This issue appears to have been existent since around November of 2023, when support for TextChatCommands in Adonis was added.

### Device

Windows

**Comment by PurpleCreativity** [comment]
This is a bug???

**Comment by break-core** [comment]
I would say it's a bug, but also a feature request at the same time. I just chose bug because this felt like a bug in how Adonis handles text chat commands.

**Comment by ccuser44** [comment]
This is hard to fix without bugs. We can either totally disable autocompltete, or disable autocomplete per user but it could cause errors with the textchat
