### ISSUE TITLE
Change files back to .lua

### ISSUE THREAD

**Issue by ccuser44** [Epix-Incorporated/Adonis#1615]
### Version channel

Nightly

### Loader version

Nightly

### What part of Adonis is this related to?

GitHub Repository

### What happened?

.luau files do not have proper syntax highlighting and many other things that .lua files have even if you have an .editorconfig file defining the syntax highlighting. Also .lua files are just superior and work with more tooling

Steps to reproduce: Open any .luau file in the Github editor

### Device

Windows

**Comment by PurpleCreativity** [comment]
Why do you use the github editor?

**Comment by PurpleCreativity** [comment]
Use Rojo + VSC?

**Comment by ccuser44** [comment]
> Use Rojo + VSC?

I'm on my laptop bc my PC is broken
Also it requires a constant re-downloading of the repo and keeping up to date with it (with my PC)

**Comment by EasternBloxxer** [comment]
> > Use Rojo + VSC?
> 
> I'm on my laptop bc my PC is broken Also it requires a constant re-downloading of the repo and keeping up to date with it (with my PC)

Your hardware being dogshit is not a valid reason to do a retarded change like this.

**Comment by EasternBloxxer** [comment]
It is Luau not lua. Why would the files be named lua?

**Comment by ccuser44** [comment]
> It is Luau not lua. Why would the files be named lua?

They used to be named .lua up to a few months. Also .lua is a valid file name for Luau files and it works with more tooling

**Comment by Dimenpsyonal** [comment]
Skill issue

**Comment by ccuser44** [comment]
> Skill issue

I guess :(

**Comment by EasternBloxxer** [comment]
> > It is Luau not lua. Why would the files be named lua?
> 
> They used to be named .lua up to a few months. Also .lua is a valid file name for Luau files and it works with more tooling

Kill yourself.

**Comment by javajuicer** [comment]
roblox uses the luau programming language. it wouldn't make sense to use a different language's file extension, even if it works.
