### ISSUE TITLE
Adonis server cleanup & shutdown cannot be turned off

### ISSUE THREAD

**Issue by zman29er** [Epix-Incorporated/Adonis#1632]
### Version channel

Stable (Default)

### Loader version

255

### What part of Adonis is this related to?

Loader/Settings

### What happened?

Version 255 (and likely any later version's) server cleanup/shutdown feature is unable to turned off. There is no listed setting in the config script and the feature is automatically turned on. 

### Steps to reproduce

Opening up a new Roblox instance will automatically start the server cleanup/shutdown feature. N/A on attempting to acquire a setting.

### Device

Windows

### Relevant log output

```shell
-- :: Adonis :: Beginning Adonis cleanup & shutdown process...
-- :: Adonis :: Saving command logs...
```

**Comment by ccuser44** [comment]
Why would you want to turn this off?

**Comment by zman29er** [comment]
> Why would you want to turn this off?

Apparently servers are only up for about 10-15 minutes before the process initiates. I don't know what the default initiation time is but that's the situation right now.

**Comment by ccuser44** [comment]
> > Why would you want to turn this off?
> 
> Apparently servers are only up for about 10-15 minutes before the process initiates. I don't know what the default initiation time is but that's the situation right now. I forgot to clarify it initially so that's on me.

But what do you mean by that? Are you saying that Adonis will initiate a shutdown even when the server is active and this happens 10-15 mimutes from the start? And if so, does this happen in game or in studio and with a studio local server or just the play button?
