### ISSUE TITLE
Anticheat false detects and kicks on team test

### ISSUE THREAD

**Issue by laagginq** [Epix-Incorporated/Adonis#1661]
### Version channel

Stable (Default)

### What part of Adonis is this related to?

Loader/Settings

### What happened?

i tried team testing my game and it would kick me for namecallindex detected even when i disabled all detections

### Steps to reproduce

1. Add adonis to your game
2. Publish and enable team create
3. Start a team test instance
4. Youll get kicked after around 10 seconds of getting in the game

### Device

Windows

**Comment by ccuser44** [comment]
#1617 Fixes
