### ISSUE TITLE
Adonis causes warning: "RunContext of LocalScript is fixed to Legacy", "New value will be ignored"

### ISSUE THREAD

**Issue by ator-dev** [Epix-Incorporated/Adonis#1664]
### Version channel

Stable (Default)

### Loader version

260

### What part of Adonis is this related to?

Other

### What happened?

On games which use Adonis, a recent update (I don't know when) caused it to start outputting the following warning:

`The RunContext of LocalScript is fixed to Legacy and cannot be changed. New value will be ignored.`

![image](https://github.com/user-attachments/assets/0e311e5b-ae77-46c2-a6a7-077d0156dcbb)

This happens, in the shown order, every time you run the game whether in the player or studio.

### Steps to reproduce

Run a game with Adonis.

### Device

Windows

**Comment by ccuser44** [comment]
#1647 fixes
