### ISSUE TITLE
Do something about audit logs

### ISSUE THREAD

**Issue by ccuser44** [Epix-Incorporated/Adonis#1694]
### Version channel

Nightly

### Loader version

Nightly

### What part of Adonis is this related to?

Other

### What happened?

There are so many problems with Audit logs.

- They just errors and lags in studio.
- They don't respect any datastore saving settings
- They cause massive datastore spam due to every command that uses audit logs always saving to a datastore.
- Code is very error prone
- The implementation inappropriately shares code between different Adonis modules
- Dublicates functionality of oldlogs
- The code doesn't use proper Adonis datastore mechanisms
- Numerous other issues

Something should be done, either about the issues or about auditlogs.

### Steps to reproduce

N/A

### Device

Windows

**Comment by ccuser44** [comment]
Related #1588

**Comment by Dimenpsyonal** [comment]
Once something is done about audit logs I can release v260. You're welcome to submit a PR to either remove them or fix them and I'll merge either

**Comment by ccuser44** [comment]
> Once something is done about audit logs I can release v260

Its not. There ae  numerous problems (including breaking bugs) and pulls to be merged to fix them

**Comment by Dimenpsyonal** [comment]
Fixed by #1698
