### ISSUE TITLE
Make the Adonis encryption cipher support the full 0-255 character range

### ISSUE THREAD

**Issue by ccuser44** [Epix-Incorporated/Adonis#1701]
### What part of Adonis is this related to?

Other

### What are you suggesting?

Make the Adonis encryption cipher support the full 0-255 character range

If someone does this however you should keep note that datastores depends on the encryption algorithm and thus you would have to use something else for them and have backwards compatibility.

**Comment by EasternBloxxer** [comment]
Remove remote encryption entirely. its a waste of time

**Comment by ccuser44** [comment]
> Remove remote encryption entirely. its a waste of time

No :P

**Comment by ccuser44** [comment]
Also new one should use bit32.bxor because it works just better.
