### ISSUE TITLE
CommandBar to autofill the prefix

### ISSUE THREAD

**Issue by xJustBen** [Epix-Incorporated/Adonis#1785]
### What part of Adonis is this related to?

User Interface

### What are you suggesting?

Autofilling the prefix when the command bar is activated.
Every other admin system does this, and would make it easier to quickly type commands.

**Comment by Dimenpsyonal** [comment]
The reason it isn't autofilled is because Adonis has 3 prefixes

**Comment by xJustBen** [comment]
> The reason it isn't autofilled is because Adonis has 3 prefixes

Yes I literally just remembered, so maybe not require a prefix to be used in the command bar?

**Comment by Dimenpsyonal** [comment]
Problem is that some different commands are seperated only by prefix. Adonis has no way of telling apart :cape from !cape other than the prefixes

**Comment by xJustBen** [comment]
Yea true I just checked this. Will close.

**Comment by sheenieboy** [comment]
I’ve got a plugin that edits all commands to use the main prefix if no other prefix is found would be a better way of doing this

**Comment by xJustBen** [comment]
Would you be able to implement it into the command bar though?

**Comment by sheenieboy** [comment]
Yes it works for the command bar

**Comment by xJustBen** [comment]
Could you attach a video of it in action?

**Comment by sheenieboy** [comment]
It wont let me add a video its too big or in wrong format but heres the code for my plugin;
`return function(Vargs)
    local server, service = Vargs.Server, Vargs.Service

    local Settings = server.Settings
    local Commands = server.Commands
    local Functions = server.Functions
    local Admin = server.Admin
    local Process = server.Process;
    local Anti = server.Anti;
    
    local client = Vargs.Client
    local Remote = server.Remote
    
    Remote.Commands.ProcessCommand = function(p: Player, args: {[number]: any})
        if Process.RateLimit(p, "Command") and type(args[1]) == "string" then
            
            if string.sub(args[1], 1, 1) ~= Settings.Prefix and string.sub(args[1], 1, 1) ~= Settings.PlayerPrefix then
                args[1] = Settings.Prefix .. args[1];
            end
            Process.Command(p, args[1], {
                Check = true
            })
        elseif Process.RateLimit(p, "RateLog") then
            Anti.Detected(p, "Log", string.format("Running commands too quickly (>Rate: %s/sec)", 1/Process.RateLimits.Command));
            warn(string.format("%s is running commands too quickly (>Rate: %s/sec)", p.Name, 1/Process.RateLimits.Command));
        end
    end;
end`
