### ISSUE TITLE
`:ckick` dose not display correctly.

### ISSUE THREAD

**Issue by feme12** [Epix-Incorporated/Adonis#1788]
### Version channel

Stable (Default)

### Loader version

261

### What part of Adonis is this related to?

Command

### What happened?

When you ckick someone and it shows the gui the title works fine but the start of the message gets cut off
![image](https://github.com/user-attachments/assets/d1a1b049-6412-4c34-b0dc-b49c58f911f0)

### Steps to reproduce

Run :ckick on a player and you will see that the message start is cut off.

### Device

Windows

**Comment by WalkerOfBacon** [comment]
Im pretty sure ik what's causing it and im gonna look into it

**Comment by feme12** [comment]
Ok also for some reason it makes my studio crash...

**Comment by WalkerOfBacon** [comment]
> Ok also for some reason it makes my studio crash...
oh yeah thats what the command does

**Comment by WalkerOfBacon** [comment]
https://github.com/Epix-Incorporated/Adonis/pull/1789
