### ISSUE TITLE
Script timeout: exhausted allowed execution time

### ISSUE THREAD

**Issue by cl1ents** [Epix-Incorporated/Adonis#779]
#148 Is still very much an issue! Might be a different function though

![image](https://user-images.githubusercontent.com/14357936/170865922-b1137a69-1ad4-41fe-9b4a-c1fb13554101.png)

**Comment by P3tray** [comment]
This is a different error to the one bandaided by Sceleratis. This is a standard script timeout. Do you have any plugins? What is in your settings file?

**Comment by cl1ents** [comment]
> This is a different error to the one bandaided by Sceleratis. This is a standard script timeout. Do you have any plugins? What is in your settings file?

![image](https://user-images.githubusercontent.com/14357936/170866416-c1266df6-7bea-4675-adb6-e80ff878787f.png)

It might have to do with the fact that our ban list is insanely big, because the line that errors is [this one](https://github.com/Sceleratis/Adonis/blob/aa76c674f8d3004c7b00c9e49adf45aafb38c39b/MainModule/Server/Shared/Service.lua#L125)

**Comment by P3tray** [comment]
> > This is a different error to the one bandaided by Sceleratis. This is a standard script timeout. Do you have any plugins? What is in your settings file?
> 
> ![image](https://user-images.githubusercontent.com/14357936/170866416-c1266df6-7bea-4675-adb6-e80ff878787f.png)
> 
> It might have to do with the fact that our ban list is insanely big, because the line that errors is [this one](https://github.com/Sceleratis/Adonis/blob/aa76c674f8d3004c7b00c9e49adf45aafb38c39b/MainModule/Server/Shared/Service.lua#L125) (We're considering just dumping the ban list in another script)
> 
> Edit: we ended up moving said ban list away from the DataStore and into the settings file, we have 2659 bans and that might the the reason why the unpack function chugs.

I can try to implement a solution today, it might work, it might not. For you, I recommend not banning 2.6k people in the future if you can help it. What the hell? What are you daily player numbers?!

**Comment by P3tray** [comment]
I am going to try to implement a version of table.unpack which yeilds periodically, possibly even using multithreading. This will be based off the LuaU source code if it's in there, if not I give up.

**Comment by P3tray** [comment]
Save some people some time in finding it, but it's obviously tasty C code

![image](https://user-images.githubusercontent.com/31691973/170869927-31a76864-898d-40d3-913e-2527f57c5793.png)

**Comment by P3tray** [comment]
https://github.com/Roblox/luau/blob/e06b5c2e28b638d31c091ca9671f0efee3f1ba51/VM/src/lbuiltins.cpp

**Comment by P3tray** [comment]
@Expertcoderz @Sceleratis @joritochip @Mudock-Yatho If you guys have a better solution to this, let me know.

Do also bear in mind that whatever this does, which I ain't read it properly yet, might not be doing it properly?
![image](https://user-images.githubusercontent.com/31691973/170870066-2a81322d-1aba-4a76-af40-824b2ae8230d.png)

**Comment by cl1ents** [comment]
> I can try to implement a solution today, it might work, it might not. For you, I recommend not banning 2.6k people in the future if you can help it. What the hell? What are you**(r)** daily player numbers?!

We'll see in the future what that solution gives us, but we [have like 4k CCU rn](https://www.roblox.com/games/5771467270/TTD-3) lol

**Comment by Sceleratis** [comment]
tbh I don't think unpack should be having any issue... it's not like it would be unpacking the banlist, just returning the table for it...

**Comment by bqsi** [comment]
Hiya, co-worker of cl1ents here

We mitigated the issue by storing the old banlist we had (the reason this issue is only happening now is because we were moving a ban list over from HD Admin) in a ModuleScript and we just gave it to the settings script instead.

The issue no longer exists.
We're happy to implement any future solutions later down the line if they'd be more beneficial.

**Comment by bqsi** [comment]
> tbh I don't think unpack should be having any issue... it's not like it would be unpacking the banlist, just returning the table for it...

I doubt it's unpack, I think it was just the size of the DS. Before I cleared it I realise it was taking up about 12.6% of the allowed storage capacity on any given DS, so it wouldn't surprise me if it was literally just taking a while

**Comment by cl1ents** [comment]
It's still kind of an odd issue, even if it is because of the DataStore being insanely big, why does it decide to not work like in 1/10 cases?
Roblox Luau (lowercase u, /ˈlu.aʊ/) quirks??

**Comment by Sceleratis** [comment]
https://github.com/Sceleratis/Adonis/issues/788

**Comment by Expertcoderz** [comment]
Is this still occurring?

**Comment by SpiralGaia** [comment]
> Is this still occurring?

Can confirm this is still occurring in my game, but I have noticed that it is less common (usually 2/3 servers have the issue, previously was near 100%)

**Comment by LawMixer** [comment]
couldn't we just for loop and get the returns and then add a task.wait()

**Comment by ccuser44** [comment]
I found something that might relate to this
![image](https://user-images.githubusercontent.com/68124053/213882446-db974194-9099-4a8b-96fc-1c37de85ce70.png)

**Comment by LiveFireExercise** [comment]
die

**Comment by WaviestBalloon** [comment]
> die

no die

**Comment by ccuser44** [comment]
Apparently people are having this issue again:
![image](https://user-images.githubusercontent.com/68124053/229303529-312ad0df-0ec4-4b72-aaac-600056096837.png)

**Comment by WaviestBalloon** [comment]
It's only April Fools, I'm *sure* they were joking

**Comment by ccuser44** [comment]
> It's only April Fools, I'm _sure_ they were joking

Lmao I didn't even realise that

**Comment by ccuser44** [comment]
Are you sure though the person getting the crash message is joking?

**Comment by P3tray** [comment]
I've said this many times before:

Follow the ostrich algorithm.

**Comment by WaviestBalloon** [comment]
Follow the ostrich algorithm.

**Comment by P3tray** [comment]
> i'm having this same issue rn ![image](https://user-images.githubusercontent.com/111817596/259187923-5482934f-b3af-40f2-a277-27be3a5ab505.png)

Have you tried using the ostrich algorithm?

**Comment by WaviestBalloon** [comment]
> i'm having this same issue rn
> ![image](https://github.com/Epix-Incorporated/Adonis/assets/111817596/5482934f-b3af-40f2-a277-27be3a5ab505)
> 
> 

Please factory reset the Roblox client.

**Comment by P3tray** [comment]
> > i'm having this same issue rn
> Please factory reset the Roblox client.
He needs to update his FTI Remote Parameters to include acceptance for all user agents regardless of SAM.

**Comment by Dimenpsyonal** [comment]
Should be fixed by thr LinkedLists

**Comment by P3tray** [comment]
> Should be fixed by the LinkedLists

It was already fixed with the ostrich algorithm.
