### ISSUE TITLE
Change :SetPrimaryPartCFrame() to :SetPivot()

### ISSUE THREAD

**Issue by Lethalitics** [Epix-Incorporated/Adonis#862]
:SetPrimaryPartCFrame() is set to be depricated in the future and is less efficient than :SetPivot() and yet still appears a number of times in in various commands. Should probably be changed at some point

**Comment by Expertcoderz** [comment]
Thanks for the suggestion.
Not super-important at the moment, but over time we'll certainly look into reviewing and editing/rewriting some parts of Adonis that still have old code.

**Comment by Expertcoderz** [comment]
> :SetPivot()

There's no such function. Only PivotTo.

**Comment by Expertcoderz** [comment]
Done. All instances of ``SetPrimaryPartCFrame`` in command modules have been replaced with ``PivotTo``.
