### ISSUE TITLE
Scriptbuilder command does not work with edit or append.

### ISSUE THREAD

**Issue by Lethalitics** [Epix-Incorporated/Adonis#863]
Neither the edit or append args actually function as intended. They seem to actually do nothing.

Steps to test:
Try command ":sb create script Test print(1)"
then try command ":sb append script Test print(2)"
after command ":sb run script Test" only 1 is printed. Same happens when you use the edit command to add a line.

**Comment by Expertcoderz** [comment]
Thanks for your report.
Scriptbuilder is a pretty old feature that's generally rarely used; I'm thinking of removing/deprecating it entirely in favor of a new script executor interface. We'll update you when either that happens or scriptbuilder is fixed.

**Comment by Expertcoderz** [comment]
Scriptbuilder is now [deprecated](https://github.com/Epix-Incorporated/Adonis/commit/d998f0301a3efd3396425b930b6d0dd02a29835c).
