### ISSUE TITLE
Help button disappearing after resetting

### ISSUE THREAD

**Issue by Cloakam** [Epix-Incorporated/Adonis#876]
- What are the steps that lead to the bug occurring? Or, how frequently does the bug occur?
Every time a player resets or dies in some way, the help button disappears.
- What would be the normally expected or desired result?
The button not disappearing
- What is the actual result (the bug)?
The help button disappears
- What is the impact of this bug?
Minor inconvenience, and you know how those go.

**Comment by LolloDev5123** [comment]
Also, it looks like Adonis still uses the default theme console when other themes are used, until the player respawns

**Comment by Expertcoderz** [comment]
> Also, it looks like Adonis still uses the default theme console when other themes are used, until the player respawns

It has always been like this.

**Comment by LolloDev5123** [comment]
Change it then

**Comment by Cloakam** [comment]
Update: I just realized that the Adonis in my game has a separate license script, meaning it could be the old version. I'll update my Adonis to the newer version and edit this message.
