### ISSUE TITLE
:bring, :to, and :tp are broken

### ISSUE THREAD

**Issue by keonipoland** [Epix-Incorporated/Adonis#877]
When using any of the teleportation commands, instead of teleporting you to the player you listed when you said the command, it teleports you to a random place on the map. I put in a new Adonis model and tried it in multiple games and every time I used a teleport command (such as :to, :bring, or :tp) it teleported me to a random spot on the map instead of teleporting me to the player I listed. (edit: Sorry I just realized I was supposed to use a certain format for the bug report)
EDIT: This issue is resolved, how do I take down this post?

**Comment by WaviestBalloon** [comment]
Seems like it is resolved. It's best to close this Issue.

**Comment by WaviestBalloon** [comment]
Ignore me. I didn't understand the edit message, apologies.
