### ISSUE TITLE
Crash/remote related commands are broken?

### ISSUE THREAD

**Issue by LolloDev5123** [Epix-Incorporated/Adonis#882]
When running any crash command (:gpucrash, :crash, :hardcrash, etc.), nothing happens on the client, very sad.
No error is outputted, which makes me believe that no remote is fired

**Comment by autodoorsdev** [comment]
Tested those commands on a fresh install on Adonis and it works fine for me

**Comment by LolloDev5123** [comment]
Probably just a me issue.
