### ISSUE TITLE
Adonis creating a lot of noise for text scraping (Localization)

### ISSUE THREAD

**Issue by intykat** [Epix-Incorporated/Adonis#883]
Recently decided to localize our game, which uses Adonis. 
Issue is, Adonis uses a lot of UI, which has the `AutoLocalize` property set to true on it. This causes Roblox to capture that text, which creates a _lot_ of noise for my translators. This happens with some of the Adonis UI, aswell as building tools and other UI related aspects. If there is any chance that we could either enable a feature to disable the property on all UI related to the admin, or to just have it disabled automatically. Thanks.

![image](https://user-images.githubusercontent.com/59971336/181811264-3ef59ecb-6942-4913-9377-e4a2e0985882.png)

I am putting this as a bug report because I do not believe this is intended behavior.

**Comment by Expertcoderz** [comment]
All elements belonging to the following GUIs now have their `AutoLocalize` property set to `false`:

* Unity theme — https://github.com/Epix-Incorporated/Adonis/commit/d2d930a17ff3a419cd82aaf607f25d4a44776254
* Dex explorer — https://github.com/Epix-Incorporated/Adonis/commit/d29a6ad204aec6f3a63eaffdf5c2848feb5d8b23

(It may still be theoretically possible that script-generated GUI objects may still have `AutoLocalize` enabled; feel free to reopen this issue in the event of that happening.)

(Fixes will be applied on release v238.)
