### ISSUE TITLE
:ungameban does not save

### ISSUE THREAD

**Issue by JustANap** [Epix-Incorporated/Adonis#888]
- What are the steps that lead to the bug occurring? Or, how frequently does the bug occur?
Insert a new Adonis loader, change the DataStore key and give self Creator permissions. Join a server and :gameban a player by name. Leave the server and rejoin to create a new one. :ungameban the player from before, then leave and create a new server. The player will still be banned.

- What would be the normally expected or desired result?
The player being unbanned would save across new servers.

- What is the actual result (the bug)?
The player's initial ban saves, but the unban does not.

- What is the impact of this bug?
Admins must unban specific players in every new server.

- (Any additional context or information eg. in the form of error messages or screenshots.)
Testing was done in both Studio's Team Test and regular Roblox servers, yields same result. The console outputs no errors or anything out of the ordinary. Waited about 30 seconds after each command to allow the banlist to update and the message to show at the top of the screen. If the ban and unban command are used in the same server without leaving, the unban DOES save for new servers.

**Comment by AustinnK** [comment]
problem is with `if type(data) == "table" and data.LaxCheck then Functions.LaxCheckMatch` on line 1016, 1064, 1114. replace these with `local CheckMatch = Functions.CheckMatch`

**Comment by happyman090** [comment]
supposedly fixed by mr expertcoderz so you can probably close this now
![image](https://user-images.githubusercontent.com/49007543/187411294-ada10ad7-051a-4291-8bcc-7fbd18fece6e.png)
