### ISSUE TITLE
Command bar opens / gets cloned twice, never re-enables chat when closed

### ISSUE THREAD

**Issue by JaksonD** [Epix-Incorporated/Adonis#895]
- What are the steps that lead to the bug occurring? Or, how frequently does the bug occur?
100% chance when opening command bar

- What would be the normally expected or desired result?
It doesn't open twice

- What is the actual result (the bug)?
It gets cloned twice to your player gui, thus adding TONS of friction to the process of executing commands + cannot open chat anymore

- What is the impact of this bug?
Very high

- (Any additional context or information eg. in the form of error messages or screenshots.)
![image](https://user-images.githubusercontent.com/77369015/183274943-64958e6a-d159-4e9e-8967-7dc28db7a852.png)
There's both of em in my player gui

Video of the bug:
https://streamable.com/r067zd

Recorded on fresh empty baseplate, assuming this is a Roblox update breaking something

**Comment by JaksonD** [comment]
Should add, no visible error messages on client nor server

**Comment by heemayy** [comment]
I thought it was something in my game messing with it. I tried opening it on a flat baseplate with adoni's only, but the same issue recurred. 

o:

**Comment by coasterteam** [comment]
Should be fixed in new servers.
