### ISSUE TITLE
Why does adonis admin roblox get rid of the chatbox and leaderboard

### ISSUE THREAD

**Issue by syrupdev** [Epix-Incorporated/Adonis#897]
Whenver I close out of the command bar, my chatbox and leaderboard are gone, and the options to select them are too.

**Comment by Expertcoderz** [comment]
This is a known bug; we're working on a fix for it soon.

**Comment by AF1011** [comment]
Same here, i'll try that changing the prefix then reinstall the system but it's doesn't work...

**Comment by coasterteam** [comment]
I am looking into this now, expect a fix soon

**Comment by coasterteam** [comment]
Should be fixed in new servers.
