### ISSUE TITLE
Capes don't seem to load their textures correctly, only show bare material.

### ISSUE THREAD

**Issue by bowlingbossninja** [Epix-Incorporated/Adonis#913]
It's as the title says, none of the capes seen to have working textures, so only their bare materials and colors show.

**Comment by NubNublet** [comment]
Yep. I'm having this issue as well. Also, it seems it will sometimes duplicate the cape, so when you make edits it just gives you a new edited cape, and you can't disable the first one.

**Comment by Expertcoderz** [comment]
Fixed in the latest manual publish.
