### ISSUE TITLE
Hat command is gone

### ISSUE THREAD

**Issue by astr0comet** [Epix-Incorporated/Adonis#917]
It was working fine just last night, but now the :hat/!hat command doesn't work. I don't know if it was just deleted, but it's concerning since we use it constantly. My friends are having the same issue, even in other games, so it's not just a game and/or user issue. Apparently, it doesn't even show in the command list according to some of them, but I haven't checked myself yet,

**Comment by P3tray** [comment]
THIS SOUNDS TERRIFYING!!!!

**Comment by DimensionalFusion** [comment]
I AGREE!!!!

**Comment by jhhspace** [comment]
OH NO!! YOU GOTTA GO HATLESS NOW 😭😭

**Comment by carter0nline** [comment]
Can confirm, as well as the disappearance of other avatar commands like ;torso

**Comment by Expertcoderz** [comment]
Fixed in the latest publish.
