### ISSUE TITLE
Watch (View) command does not work when Streaming is enabled

### ISSUE THREAD

**Issue by RabbyDevs** [Epix-Incorporated/Adonis#920]
Expected behavior: You are able to view players which are not streamed in yet.

Actual behavior: Your camera completely separates from Local Player and is unable to move until you view yourself.

How to reproduce: Go into studio > Make a game > Enable Streaming > Make a teleport between 1 part of the map which will not be streamed in and your spawn > Try to use the View (Watch) command on the player who is on that not streamed section.

**Comment by P3tray** [comment]
This can be fixed by Adonis freezing your own character (to stop it becoming one with the void - may be problematic with users wishing to troll the leftover limp corpse) and changing the RenderFocus or whateverthefuckitiscalled to the players head.

**Comment by Dimenpsyonal** [comment]
Why wouldn't adonis do that automatically tho

**Comment by Dimenpsyonal** [comment]
Should be fixed by the ReplicationFocus

**Comment by P3tray** [comment]
> Should be fixed by the ReplicationFocus

woohoo
