### ISSUE TITLE
Error loading Icon

### ISSUE THREAD

**Issue by ItsOaky** [Epix-Incorporated/Adonis#925]
Hello! When changing the theme within Adonis in settings (before starting), the icon you choose does not seem to work correctly, but instead replaces the image with you profile picture. Does not affect performance but does affect appearance.

**Comment by P3tray** [comment]
> Hello! When changing the theme within Adonis in settings (before starting), the icon you choose does not seem to work correctly, but instead replaces the image with you profile picture. Does not affect performance but does affect appearance.

That's because you changed to a theme which force overrides the helpbutton irrespective of the helpbutton image to your face. Pretty sure you're using the Unity theme by @LolloDev5123? If so, a fix may be possible.

**Comment by LolloDev5123** [comment]
Hi! Would you mind sharing screenshots of said issue? I believe this is something new.

**Comment by ItsOaky** [comment]
I am so sorry! I've been super busy recently, although I am back!
Yea, I can give you some screenshots, not going to lie though, I kind of like the help button thing as it shows the avatar insteal of the question mark icon! Although, I'm not mad!

**Comment by ItsOaky** [comment]
but of course, my apologies for such late responses, you're welcome to spam my email if you need an urgent response!

**Comment by LolloDev5123** [comment]
Hi! I think I figured out your issue. In the current Unity version, the HelpButton shows the player's avatar, and does not currently support customization of the HelpButton Image from the Settings.   
I plan to support this feature though

**Comment by ItsOaky** [comment]
That would be cool, or add an option to pick if you want your avatar or the help system image! Just an epiphany. But either or, thanks much!

Gav
________________________________

**Comment by ItsOaky** [comment]
This is way over-the-top, but for Adonis, make a web portal! It's EXTREMELY difficult, but is soo cool when it's done! Basically, ad users to the ban list from there, add/remove certain permissions, and even kick people remotely, if at all possible.

Just an idea,
Gav
________________________________

**Comment by P3tray** [comment]
> This is way over-the-top, but for Adonis, make a web portal! It's EXTREMELY difficult, but is soo cool when it's done! Basically, ad users to the ban list from there, add/remove certain permissions, and even kick people remotely, if at all possible. Just an idea, 

It already exists.

https://adonis.dev/login?redirect=https://adonis.dev/select

**Comment by Sceieratis** [comment]
Sounds like a user error. Have you tried refreshing the MD5 Hash in Adonis? 
The case will be permanently closed and locked if a response is not received within 6 hours.

**Comment by ccuser44** [comment]
This is intentional

**Comment by Dimenpsyonal** [comment]
I will fix this in a bit; adding custom icon logic to unity shouldn't be that hard...

**Comment by Dimenpsyonal** [comment]
Fixed

**Comment by P3tray** [comment]
> Fixed

he fixed it in a bit
