### ISSUE TITLE
Web panel authentication failure

### ISSUE THREAD

**Issue by ItsOaky** [Epix-Incorporated/Adonis#947]
So, while I'm not the best at Lua, I am good with general web development, your authentication service provider may need to be updated! I am not able to create a new account because evidently my email isn't valid! It's your standard outlook account! I also don't like logging in with discord, simply because I just don't. No questions needed.

Thanks,
Gav

**Comment by GalacticInspired** [comment]
pls simplify

**Comment by P3tray** [comment]
> pls simplify

![image](https://user-images.githubusercontent.com/31691973/202566884-81a823d3-5dcd-41a5-aafc-cba6c5de8665.png)

**Comment by ItsOaky** [comment]
Okay, so on the web portal, you go to sign up/create an account, and it gives you a message that your email/username is already taken or is unavailable for use... I don't know what service you go through (I recommend Ory), but it is super unreliable, even logging in with discord doesn't work because the redirect is invalid.

**Comment by ItsOaky** [comment]
If you want, I can go to nerd-edition of that!

**Comment by P3tray** [comment]
> Okay, so on the web portal, you go to sign up/create an account, and it gives you a message that your email/username is already taken or is unavailable for use... I don't know what service you go through (I recommend Ory), but it is super unreliable, even logging in with discord doesn't work because the redirect is invalid.

We made it.

**Comment by ItsOaky** [comment]
It's nice! But it doesn't seem to be working quite correctly!
________________________________

**Comment by joritochip** [comment]
I would say it is currently not recommended to use the existing web panel. We are in the process of developing a new version from scratch which should address most if not all of the issues currently present in the existing release.

**Comment by P3tray** [comment]
> I would say it is currently not recommended to use the existing web panel. **We are in the process of developing a new version** from scratch which should address most if not all of the issues currently present in the existing release.

I've seen horses full of less shit.

**Comment by ItsOaky** [comment]
Lol, fair enough

**Comment by Sceieratis** [comment]
Please check your inbox for further information in the Adonis Newsletter.

**Comment by Dimenpsyonal** [comment]
Webpanel no longer exists sooo... We fixed it? Well done us!
