### ISSUE TITLE
ResetPlayerGuiOnSpawn to false maybe affecting adonis gui not poping up in the player guis

### ISSUE THREAD

**Issue by Rolexboy88cool** [Epix-Incorporated/Adonis#949]
- What are the steps that lead to the bug occurring? Or, how frequently does the bug occur?
run this command in the roblox studio console game.StarterGui.ResetPlayerGuiOnSpawn = false
- What would be the normally expected or desired result?
 when joining the game sometimes adonis guis wont show aka "cmds gui, command bar"
- What is the actual result (the bug)?
 when joining the game sometimes adonis guis wont show aka "cmds gui, command bar"
- What is the impact of this bug?
 its annoying and people have to do !rejoin to and rarely get it fixed
- (Any additional context or information eg. in the form of error messages or screenshots.)

**Comment by Rolexboy88cool** [comment]
[BUG CLOSED FOR NOW] LOOKING INTO

**Comment by EgizianoEG** [comment]
hmmm.. why would someone make the entire playergui: ResetPlayerGuiOnSpawn = false
just why

**Comment by WaviestBalloon** [comment]
> hmmm.. why would someone make the entire playergui: ResetPlayerGuiOnSpawn = false just why

True, but I would have throught Adonis would automatically insert the GUI on command.

**Comment by WaviestBalloon** [comment]
Did some testing for this issue.

No Adonis icon
![image](https://user-images.githubusercontent.com/31796727/219612472-0c5cf0fe-fe89-4b74-9ebb-716391381e0b.png)

Banner messages still work, same with the blur message
![image](https://user-images.githubusercontent.com/31796727/219612609-8a8a7e37-d48d-44e6-9046-0e5379221801.png)
![image](https://user-images.githubusercontent.com/31796727/219612704-31404b4c-2758-4105-99dc-d4175a7620a4.png)

All of the interfaces work perfectly fine
![image](https://user-images.githubusercontent.com/31796727/219613055-777b2361-1859-4e31-9671-9478b202b933.png)

**Comment by WaviestBalloon** [comment]
@Rolexboy88cool can you give us more evidence of the issue? You've not posted any screenshots or screen-caps of the issue at play, from my testing it works as intended apart from the Adonis Help icon not showing up.

**Comment by LiveFireExercise** [comment]
i don’t think so

**Comment by WaviestBalloon** [comment]
@Expertcoderz I think this can be closed now
