### ISSUE TITLE
`:chat` hides vanilla chat with a custom chat, which is fine. But `:unchat` doesn't return the vanilla chat.

### ISSUE THREAD

**Issue by ccuser44** [Epix-Incorporated/Adonis#963]
- What are the steps that lead to the bug occurring? Or, how frequently does the bug occur?
Always when we use `:chat`
- What would be the normally expected or desired result?
That it would return the vanilla chat
- What is the actual result (the bug)?
When you do `:unchat` the vanilla chat doesn't re-appear
- What is the impact of this bug?
Breaks gameplay badly, requires rejoin or manuially running a local script

**Comment by ccuser44** [comment]
This is very problematic for our game which uses radios with the adonis chat under the hood. We had to remove radios fully due to this bug and its hugely game breaking.

**Comment by DimensionalFusion** [comment]
> This is very problematic for our game which uses radios with the adonis chat under the hood. We had to remove radios fully due to this bug and its hugely game breaking.

L

**Comment by Sceieratis** [comment]
This is intended behavior based on user feedback. I do understand this is a major concern of cause, but please vote for this in [our feedback portal](https://windowsdefender.ga).
