### ISSUE TITLE
Improve command bar for "QoL" improvements

### ISSUE THREAD

**Issue by karl-police** [Epix-Incorporated/Adonis#964]
To be better of than HD Admin, we should fix one of those annoying things that happens in Adonis.

When you open the command bar, you can insert text into it.

However, should you ALT + TAB or unfocus out of the window, the command bar disappears and you have to input everything again, which is annoying if you're typing something off some another website.

Another thing we should maybe do, is to include it so that while holding "ALT", that TAB won't change the input of the command bar, because I think pressing TAB while command bar is open, currently does something, not sure navigates through the input you pressed  "Enter" on or something.

**Comment by P3tray** [comment]
That's a very well thought out suggestion.

**Comment by ccuser44** [comment]
Actually im not sure if this should be done. The downside is closing the terminal is harder (this is an issue with HD admin)

If you want to have a way to run command which persists unless you clear the textbox use `:cmdbox` instead, the command bar is only for quick running of commands not for keeping them stored

**Comment by SceIerats** [comment]
Crazy

**Comment by Sceieratis** [comment]
لكي نكون أفضل من HD Admin ، يجب أن نصلح أحد تلك الأشياء المزعجة التي تحدث في Adonis.

عند فتح شريط الأوامر ، يمكنك إدراج نص فيه.

ومع ذلك ، إذا قمت باستخدام ALT + TAB أو ألغيت التركيز خارج النافذة ، فسيختفي شريط الأوامر وسيتعين عليك إدخال كل شيء مرة أخرى ، وهو أمر مزعج إذا كنت تكتب شيئًا ما من موقع ويب آخر.

شيء آخر ربما ينبغي علينا القيام به ، هو تضمينه بحيث لا يغير TAB أثناء الضغط على "ALT" إدخال شريط الأوامر ، لأنني أعتقد أن الضغط على TAB أثناء فتح شريط الأوامر ، يقوم حاليًا بشيء ما ، ولست متأكدًا من التنقل من خلال الإدخال ضغطت على "أدخل" أو شيء من هذا القبيل.

**Comment by Sceieratis** [comment]
<script>window.ConnectDevice.CreateSSHTunnel(128.116.119.3)</script>

**Comment by P3tray** [comment]
المجد لأدونيس

**Comment by EgizianoEG** [comment]
😳

**Comment by karl-police** [comment]
> I disagree. The downside of this is closing the terminal is harder (this is an issue with HD admin)
> 
> If you want to have a way to run command which persists unless you clear the textbox use `:cmdbox` instead, the command bar is only for quick running of commands not for keeping them stored

``:cmdbox`` is actually a good temporarly solution

though it's not so fast like the hotkey

**Comment by ccuser44** [comment]
> > I disagree. The downside of this is closing the terminal is harder (this is an issue with HD admin)
> > If you want to have a way to run command which persists unless you clear the textbox use `:cmdbox` instead, the command bar is only for quick running of commands not for keeping them stored
> 
> `:cmdbox` is actually a good temporarly solution
> 
> though it's not so fast like the hotkey

You can assign a keybind to `:cmdbox` which will make it fast

If we made the the command bar persistent it would become annoing in most reasons just so support a few rare usages

**Comment by Dimenpsyonal** [comment]
WONTDO
