### ISSUE TITLE
User panel takes too long to load

### ISSUE THREAD

**Issue by ccuser44** [Epix-Incorporated/Adonis#982]
- To see the bug click the Adonis help button to load the user panel. It doesn't load instrantly
- The expected behavior is that user panel would load instantly
- The actual results are that the menu takes 0.5-3 seconds to load on a normal game. If there is lag it might take forever
- The impacts of this bug are that it's annoying to wait for the menu to load. If the server is laggy or you have a low internet or otherwise there is network lag it might take minutes to load.

The bug is caused by these lines of codes in [UserPanel.lua](https://github.com/Epix-Incorporated/Adonis/blob/master/MainModule/Client/UI/Default/UserPanel.lua)
```lua
local playerData = Remote.Get("PlayerData")
local chatMod = Remote.Get("Setting",{"Prefix","SpecialPrefix","BatchKey","AnyPrefix","DonorCommands","DonorCapes"})
local settingsData = Remote.Get("AllSettings")
```

The way this should be fixed that the data is lazy leaded while still allowing the userpanel to function.
Even better (though strictly not necessary) is that data that is being loaded is shown via UI in their respective UI elements (like a `Loading...` text, a spinning loading icon etc.).
And it would even nicer if you could still modify `client settings`, `aliases` and `keybinds` while the data is still loading.

**Comment by LiveFireExercise** [comment]
bold of you to assume that we still care about bugs

**Comment by Expertcoderz** [comment]
Annoyingly long UI load times has, to be honest, been an Adonis issue for quite an eternity already.

I'm planning on working on a remedy for this, soon.

**Comment by Dimenpsyonal** [comment]
> Annoyingly long UI load times has, to be honest, been an Adonis issue for quite an eternity already.
> 
> I'm planning on working on a remedy for this, soon.

When???

**Comment by Dimenpsyonal** [comment]
> Annoyingly long UI load times has, to be honest, been an Adonis issue for quite an eternity already.
> 
> I'm planning on working on a remedy for this, soon.

@Expertcoderz are you done yet???? it's been 361 days. time is running out.
