### ISSUE TITLE
Adonis saves default data in datastores

### ISSUE THREAD

**Issue by ccuser44** [Epix-Incorporated/Adonis#983]
- The expected results are that Adonis only saves data to the datastores when absolutely necessary. If there is no data to save it shouldnt even save an empty table
- The actual results are that Adonis saves all of the player data (even when not necessary)
- The impacts of this bug is that a lot of unnecessary data being saved and loaded lagging the datastores. If there are a lot of players in the server this causes datastores and other internal HTTP thing will fail resulting in datastores not working and potentially breaking other stuff like `InsertService`, Chat filters, Filtering and sometimes serverside corescripts and other internal Roblox code resulting in odd errors and weird gameplay breakage.

The worst part is that it saves all the groups a player is in (for some weird reason :/)
I feel like this bug has been at least since 2020 but I have an feeling that it has been happening a lot before
This issue mostly affects big games with lots of players
Also its an issue if the game changes the default settings all of the players that have joined before retain the old settings even though they haven't modified them

Pictures of unnecessary data saved by Adonis retrieved via OpenCloud API:
![image](https://user-images.githubusercontent.com/68124053/213882328-837bf76b-c0d9-4e94-8867-f019e2336e48.png)
![image](https://user-images.githubusercontent.com/68124053/213882330-f55efc34-0802-4d36-8040-f7857318ac84.png)
![image](https://user-images.githubusercontent.com/68124053/213882335-f22e5066-7b98-4172-9832-1afa81333786.png)

Screenshots of errors:
![image](https://user-images.githubusercontent.com/68124053/213881031-1ac4dfe7-6e77-45b6-b347-ec9c31781e63.png)
![image](https://user-images.githubusercontent.com/68124053/213881035-6d8651ee-e03b-433e-a9f3-96102e1612d0.png)
![image](https://user-images.githubusercontent.com/68124053/213881911-15a3060f-7bac-432c-8239-e1c2cdfaa29f.png)

People reporting error:
![image](https://user-images.githubusercontent.com/68124053/213882605-cae5bee0-8c33-4cea-a303-479afb558885.png)
![image](https://user-images.githubusercontent.com/68124053/213881996-1353f2df-fb1e-4c34-812f-08bbebd5a048.png)
![image](https://user-images.githubusercontent.com/68124053/213882086-b3f18452-a201-4ded-ad7d-0b353000a99c.png)
![image](https://user-images.githubusercontent.com/68124053/213882124-b81984f0-a195-4670-8ff4-aa38bbf98711.png)
![image](https://user-images.githubusercontent.com/68124053/213883347-f0e280de-e5bc-48cb-89c0-4b1f9b5a3d02.png)
![image](https://user-images.githubusercontent.com/68124053/213888730-68cd1869-5a18-4ec4-a927-65428d8d9177.png)
![image](https://user-images.githubusercontent.com/68124053/213882164-c392651e-a05f-4408-a276-8c2f44fab6af.png)
![image](https://user-images.githubusercontent.com/68124053/213882181-8a4e4e55-9b0e-4e29-8039-7469c7c05dde.png)
![image](https://user-images.githubusercontent.com/68124053/213882231-98489888-719c-43db-9bee-0c994a4ffe49.png)
![image](https://user-images.githubusercontent.com/68124053/213882366-fa9f905d-00c9-44cc-9c21-b2dc77cb9b19.png)
![image](https://user-images.githubusercontent.com/68124053/213888750-689ab3a5-1a23-4678-8e00-94be48b5d0bc.png)
![image](https://user-images.githubusercontent.com/68124053/213882823-2b2fe447-2a85-4cca-8516-9b61ff42c660.png)
![image](https://user-images.githubusercontent.com/68124053/213882844-038b47ad-1ef6-40ad-a176-cab341f80ebf.png)
![image](https://user-images.githubusercontent.com/68124053/213888778-9269a8f4-093d-4ca5-b674-3cefb68af402.png)
![image](https://user-images.githubusercontent.com/68124053/213882994-ba6485ae-87a3-47b4-a263-ac150644231a.png)

**Comment by LiveFireExercise** [comment]
Smh don’t give problems if you don’t offer solutions

**Comment by ccuser44** [comment]
I've found the culprits to this which are the 
![image](https://user-images.githubusercontent.com/68124053/215315991-eddd493c-b191-4044-815b-6b33ea5b6521.png)
![image](https://user-images.githubusercontent.com/68124053/215315996-ef9340c3-5aa4-4b48-941b-c56b74a84c0d.png)
functions.

Culprit 1 is the `SavePlayerData` function which saves unnecessary default data even though it doesn't have to happen. (This happens during player leave which isn't that big of a deal on it's own). But the worst part is that it happens every 30 seconds for every player because of this code:
![image](https://user-images.githubusercontent.com/68124053/215316473-d403fdd3-b69a-4acd-8594-d27d53636df5.png)
The problem with this is that it saves the data for all players every 30 seconds even if it doesn't have to be saved.
Now a very simple fix to this issue is to simply not save player data if it's the default. I think `Core.DefaultPlayerData` allows to do this but even if it doesn't it's very trivial to code in.

Culprit 2 is the `DefaultPlayerData` Now this isn't that much of an issue and honestly the best way to fix this is to fix Culprit 1. As this function is necessary for Adonis to load and check data
![image](https://user-images.githubusercontent.com/68124053/215317198-54e657ab-0fc1-4844-8fde-d47a7263f25f.png)
